In [1]:
# 어제 데이터 복습

import pandas as pd

url = "http://freakonometrics.free.fr/german_credit.csv"
german = pd.read_csv(url)

In [2]:
german.head()

Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18   
1              1                1                           9   
2              1                2                          12   
3              1                1                          12   
4              1                1                          12   

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049   
1                                  4        0           2799   
2                                  2        9            841   
3                                  4        0           2122   
4                                  4        0           2171   

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4   
1                     1                             3                    2   
2                     2                             4                    2   
3                     1                             3                    3   
4                     1                             3                    4   

   Sex & Marital Status  ...  Duration in Current address  \
0                     2  ...                            4   
1                     3  ...                            2   
2                     2  ...                            4   
3                     3  ...                            2   
4                     3  ...                            4   

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3   
1                              1           36                   3   
2                              1           23                   3   
3                              1           39                   3   
4                              2           38                   1   

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3   
1                  1                           2           3   
2                  1                           1           2   
3                  1                           2           2   
4                  2                           2           2   

   No of dependents  Telephone  Foreign Worker  
0                 1          1               1  
1                 2          1               1  
2                 1          1               1  
3                 2          1               2  
4                 1          1               2  

[5 rows x 21 columns]

In [3]:
german.shape

(1000, 21)

In [4]:
german.columns

Index(['Creditability', 'Account Balance', 'Duration of Credit (month)',
       'Payment Status of Previous Credit', 'Purpose', 'Credit Amount',
       'Value Savings/Stocks', 'Length of current employment',
       'Instalment per cent', 'Sex & Marital Status', 'Guarantors',
       'Duration in Current address', 'Most valuable available asset',
       'Age (years)', 'Concurrent Credits', 'Type of apartment',
       'No of Credits at this Bank', 'Occupation', 'No of dependents',
       'Telephone', 'Foreign Worker'],
      dtype='object')

In [5]:
german.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Creditability                      1000 non-null   int64
 1   Account Balance                    1000 non-null   int64
 2   Duration of Credit (month)         1000 non-null   int64
 3   Payment Status of Previous Credit  1000 non-null   int64
 4   Purpose                            1000 non-null   int64
 5   Credit Amount                      1000 non-null   int64
 6   Value Savings/Stocks               1000 non-null   int64
 7   Length of current employment       1000 non-null   int64
 8   Instalment per cent                1000 non-null   int64
 9   Sex & Marital Status               1000 non-null   int64
 10  Guarantors                         1000 non-null   int64
 11  Duration in Current address        1000 non-null   int64
 12  Most valuable availab

In [6]:
german.tail()

Creditability  Account Balance  Duration of Credit (month)  \
995              0                1                          24   
996              0                1                          24   
997              0                4                          21   
998              0                2                          12   
999              0                1                          30   

     Payment Status of Previous Credit  Purpose  Credit Amount  \
995                                  2        3           1987   
996                                  2        0           2303   
997                                  4        0          12680   
998                                  2        3           6468   
999                                  2        2           6350   

     Value Savings/Stocks  Length of current employment  Instalment per cent  \
995                     1                             3                    2   
996                     1                             5                    4   
997                     5                             5                    4   
998                     5                             1                    2   
999                     5                             5                    4   

     Sex & Marital Status  ...  Duration in Current address  \
995                     3  ...                            4   
996                     3  ...                            1   
997                     3  ...                            4   
998                     3  ...                            1   
999                     3  ...                            4   

     Most valuable available asset  Age (years)  Concurrent Credits  \
995                              1           21                   3   
996                              1           45                   3   
997                              4           30                   3   
998                              4           52                   3   
999                              2           31                   3   

     Type of apartment  No of Credits at this Bank  Occupation  \
995                  1                           1           2   
996                  2                           1           3   
997                  3                           1           4   
998                  2                           1           4   
999                  2                           1           3   

     No of dependents  Telephone  Foreign Worker  
995                 2          1               1  
996                 1          1               1  
997                 1          2               1  
998                 1          2               1  
999                 1          1               1  

[5 rows x 21 columns]

In [7]:
german.isnull().sum()

Creditability                        0
Account Balance                      0
Duration of Credit (month)           0
Payment Status of Previous Credit    0
Purpose                              0
Credit Amount                        0
Value Savings/Stocks                 0
Length of current employment         0
Instalment per cent                  0
Sex & Marital Status                 0
Guarantors                           0
Duration in Current address          0
Most valuable available asset        0
Age (years)                          0
Concurrent Credits                   0
Type of apartment                    0
No of Credits at this Bank           0
Occupation                           0
No of dependents                     0
Telephone                            0
Foreign Worker                       0
dtype: int64

In [8]:
german.describe()

Creditability  Account Balance  Duration of Credit (month)  \
count    1000.000000      1000.000000                 1000.000000   
mean        0.700000         2.577000                   20.903000   
std         0.458487         1.257638                   12.058814   
min         0.000000         1.000000                    4.000000   
25%         0.000000         1.000000                   12.000000   
50%         1.000000         2.000000                   18.000000   
75%         1.000000         4.000000                   24.000000   
max         1.000000         4.000000                   72.000000   

       Payment Status of Previous Credit      Purpose  Credit Amount  \
count                         1000.00000  1000.000000     1000.00000   
mean                             2.54500     2.828000     3271.24800   
std                              1.08312     2.744439     2822.75176   
min                              0.00000     0.000000      250.00000   
25%                              2.00000     1.000000     1365.50000   
50%                              2.00000     2.000000     2319.50000   
75%                              4.00000     3.000000     3972.25000   
max                              4.00000    10.000000    18424.00000   

       Value Savings/Stocks  Length of current employment  \
count           1000.000000                   1000.000000   
mean               2.105000                      3.384000   
std                1.580023                      1.208306   
min                1.000000                      1.000000   
25%                1.000000                      3.000000   
50%                1.000000                      3.000000   
75%                3.000000                      5.000000   
max                5.000000                      5.000000   

       Instalment per cent  Sex & Marital Status  ...  \
count          1000.000000            1000.00000  ...   
mean              2.973000               2.68200  ...   
std               1.118715               0.70808  ...   
min               1.000000               1.00000  ...   
25%               2.000000               2.00000  ...   
50%               3.000000               3.00000  ...   
75%               4.000000               3.00000  ...   
max               4.000000               4.00000  ...   

       Duration in Current address  Most valuable available asset  \
count                  1000.000000                    1000.000000   
mean                      2.845000                       2.358000   
std                       1.103718                       1.050209   
min                       1.000000                       1.000000   
25%                       2.000000                       1.000000   
50%                       3.000000                       2.000000   
75%                       4.000000                       3.000000   
max                       4.000000                       4.000000   

       Age (years)  Concurrent Credits  Type of apartment  \
count   1000.00000         1000.000000        1000.000000   
mean      35.54200            2.675000           1.928000   
std       11.35267            0.705601           0.530186   
min       19.00000            1.000000           1.000000   
25%       27.00000            3.000000           2.000000   
50%       33.00000            3.000000           2.000000   
75%       42.00000            3.000000           2.000000   
max       75.00000            3.000000           3.000000   

       No of Credits at this Bank   Occupation  No of dependents    Telephone  \
count                 1000.000000  1000.000000       1000.000000  1000.000000   
mean                     1.407000     2.904000          1.155000     1.404000   
std                      0.577654     0.653614          0.362086     0.490943   
min                      1.000000     1.000000          1.000000     1.000000   
25%                      1.000000     3.000000          1.000000     1.000000   
50%           

In [9]:
print(german['Duration of Credit (month)'].value_counts().sort_index())

print(german['Duration of Credit (month)'].value_counts().sort_values())

4       6
5       1
6      75
7       5
8       7
9      49
10     28
11      9
12    179
13      4
14      4
15     64
16      2
18    113
20      8
21     30
22      2
24    184
26      1
27     13
28      3
30     40
33      3
36     83
39      5
40      1
42     11
45      5
47      1
48     48
54      2
60     13
72      1
Name: Duration of Credit (month), dtype: int64
72      1
26      1
47      1
40      1
5       1
16      2
22      2
54      2
33      3
28      3
13      4
14      4
45      5
39      5
7       5
4       6
8       7
20      8
11      9
42     11
60     13
27     13
10     28
21     30
30     40
48     48
9      49
15     64
6      75
36     83
18    113
12    179
24    184
Name: Duration of Credit (month), dtype: int64


In [10]:
german_sample = german[['Creditability', 'Duration of Credit (month)',
                        'Purpose', 'Credit Amount']]

print(german_sample.min())
print(german_sample.max())
print(german_sample.mean())

Creditability                   0
Duration of Credit (month)      4
Purpose                         0
Credit Amount                 250
dtype: int64
Creditability                     1
Duration of Credit (month)       72
Purpose                          10
Credit Amount                 18424
dtype: int64
Creditability                    0.700
Duration of Credit (month)      20.903
Purpose                          2.828
Credit Amount                 3271.248
dtype: float64


In [11]:
# 샘플 df 구성

german_sample1 = german[['Duration of Credit (month)',
                        'Credit Amount',
                        'Age (years)'
                        ]]
german_sample1.head()

Duration of Credit (month)  Credit Amount  Age (years)
0                          18           1049           21
1                           9           2799           36
2                          12            841           23
3                          12           2122           39
4                          12           2171           38

In [12]:
# 변수 간의 상관관계
# 범위는 -1 ~ 1, 1에 가까울수록 상관관계 높음(자기와의 관계는 1)

german_sample1.corr()

Duration of Credit (month)  Credit Amount  \
Duration of Credit (month)                    1.000000       0.624988   
Credit Amount                                 0.624988       1.000000   
Age (years)                                  -0.037550       0.032273   

                            Age (years)  
Duration of Credit (month)    -0.037550  
Credit Amount                  0.032273  
Age (years)                    1.000000

In [13]:
# 공분산; 분포도의 관계
# 클수록 관계가 큼
german_sample1.cov()

Duration of Credit (month)  Credit Amount  \
Duration of Credit (month)                  145.415006   2.127401e+04   
Credit Amount                             21274.007063   7.967927e+06   
Age (years)                                  -5.140567   1.034203e+03   

                            Age (years)  
Duration of Credit (month)    -5.140567  
Credit Amount               1034.202787  
Age (years)                  128.883119

In [14]:
# groupby

german['Credit Amount'].groupby(german['Type of apartment'])
# 샘플의 컬럼을 뽑아서, 다른 컬럼의 그룹을 만듦

# 리스트화
list(german['Credit Amount'].groupby(german['Type of apartment']))

# 변수화; 집계해서 리스트를 임시저장
german_grouped = german['Credit Amount'].groupby(german['Type of apartment'])
print(list(german_grouped))

# 그룹화의 평균
print(german_grouped.mean())

[(1, 0      1049
1      2799
2       841
3      2122
5      2241
       ... 
983    1882
989    2718
993    3966
994    6199
995    1987
Name: Credit Amount, Length: 179, dtype: int64), (2, 4      2171
6      3398
7      1361
8      1098
12     1957
       ... 
988     976
990     750
996    2303
998    6468
999    6350
Name: Credit Amount, Length: 714, dtype: int64), (3, 29      4796
44      1239
69      2032
125     5103
146     2964
       ...  
971     8318
979     3386
991    12579
992     7511
997    12680
Name: Credit Amount, Length: 107, dtype: int64)]
Type of apartment
1    3122.553073
2    3067.257703
3    4881.205607
Name: Credit Amount, dtype: float64


In [15]:
# 두개 그룹화; 여러 개면 리스트형으로 감싸야 함

german_group2 = german['Credit Amount'].groupby([german['Purpose'],
                                                 german['Type of apartment']
                                                ])
list(german_group2)[0]

german_group2.mean()

Purpose  Type of apartment
0        1                    2597.225000
         2                    2811.024242
         3                    5138.689655
1        1                    5037.086957
         2                    4915.222222
         3                    6609.923077
2        1                    2727.354167
         2                    3107.450820
         3                    4100.181818
3        1                    2199.763158
         2                    2540.533040
         3                    2417.333333
4        1                    1255.500000
         2                    1546.500000
5        1                    1522.000000
         2                    2866.000000
         3                    2750.666667
6        1                    3156.444444
         2                    2492.423077
         3                    4387.266667
8        1                     902.000000
         2                    1243.875000
9        1                    5614.125000
       

In [16]:
# 그룹 간 반복

german_sample3 = german[['Type of apartment',
                         'Sex & Marital Status',
                         'Credit Amount'
                        ]]

german_grouped3 = german_sample3.groupby('Type of apartment')

list(german_grouped3)

[(1,
       Type of apartment  Sex & Marital Status  Credit Amount
  0                    1                     2           1049
  1                    1                     3           2799
  2                    1                     2            841
  3                    1                     3           2122
  5                    1                     3           2241
  ..                 ...                   ...            ...
  983                  1                     2           1882
  989                  1                     2           2718
  993                  1                     2           3966
  994                  1                     3           6199
  995                  1                     3           1987
  
  [179 rows x 3 columns]),
 (2,
       Type of apartment  Sex & Marital Status  Credit Amount
  4                    2                     3           2171
  6                    2                     3           3398
  7                    2      

In [17]:
for type1, group in german_grouped3:
    print('type1')
    print(group.head(3))

type1
   Type of apartment  Sex & Marital Status  Credit Amount
0                  1                     2           1049
1                  1                     3           2799
2                  1                     2            841
type1
   Type of apartment  Sex & Marital Status  Credit Amount
4                  2                     3           2171
6                  2                     3           3398
7                  2                     3           1361
type1
    Type of apartment  Sex & Marital Status  Credit Amount
29                  3                     3           4796
44                  3                     3           1239
69                  3                     3           2032


In [18]:
german_group3 = german_sample3.groupby(['Type of apartment',
                                        'Sex & Marital Status',
                                       ])
list(german_group3)[0]

((1, 1),
      Type of apartment  Sex & Marital Status  Credit Amount
 369                  1                     1           3021
 777                  1                     1           3384
 797                  1                     1           2319
 857                  1                     1           2302
 932                  1                     1           1223
 956                  1                     1           2767)

In [19]:
for (type1, sex), group in german_sample3.groupby(['Type of apartment',
                                                   'Sex & Marital Status',
                                                  ]):
    print(type1, sex)
    print(group.head(3))

1 1
     Type of apartment  Sex & Marital Status  Credit Amount
369                  1                     1           3021
777                  1                     1           3384
797                  1                     1           2319
1 2
   Type of apartment  Sex & Marital Status  Credit Amount
0                  1                     2           1049
2                  1                     2            841
9                  1                     2           3758
1 3
   Type of apartment  Sex & Marital Status  Credit Amount
1                  1                     3           2799
3                  1                     3           2122
5                  1                     3           2241
1 4
    Type of apartment  Sex & Marital Status  Credit Amount
11                  1                     4           6187
14                  1                     4           1936
17                  1                     4           3213
2 1
     Type of apartment  Sex & Marital St

# NumPy

과학적 계산을 위한 라이브러리

다차원 배열; 리스트, 튜플 등은 일차원 데이터

데이터 분석보다, 파이썬의 수치 연산에 특화, 빠른 속도

자체의 데이터 구조; ndarray

## np 기본

In [20]:
# import

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# 4개 기본적으로 실행

# 각각의 버전을 확인
print('pandas ver = ', pd.__version__)
print('numpy ver = ', np.__version__)

pandas ver =  1.2.4
numpy ver =  1.20.1


In [21]:
# ndarray 생성
# 리스트 구조와는 다름

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [22]:
# 초기값 설정; n차원 행렬 생성

np.zeros((3, 3))
np.ones((2, 2))
np.empty((4, 4)) # 공백이지만 수치로 표시

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.78020984e-306],
       [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
        6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        8.45606157e-307],
       [6.23061763e-307, 1.11261570e-306, 9.34613864e-307,
        1.69120552e-306]])

In [23]:
# py의 range와 유사한 함수
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# 배열의 내용 확인

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
# 모양
# 행/렬 표현하지 않고 축 개념 사용
# 0번 축, 1번 축, ...
arr.shape

(2, 3)

In [26]:
arr.ndim # 몇 차원인지

2

In [27]:
arr.dtype # 들어간 데이터의 타입

dtype('int32')

In [28]:
# 형 변환
arr_int = np.arange(4)
arr_float = arr_int.astype(np.float64)
arr_float.dtype # 소수점 추가됨

dtype('float64')

In [29]:
np.array(['a', 'b', 'c'])

arr_str = np.array(['1', '2', '3'])
arr_str.dtype

arr_int = arr_str.astype(np.int64)
arr_int

arr_str1 = np.array(['a', 'b', 'c'])
# 문자열은 숫자로 형 변환 불가

In [30]:
# 연산

arr1 = np.array([[1, 2,], [3, 4]])
arr1

np.arange(1, 5)

# 1차원을 2차원으로 나누기; 갯수가 맞지 않으면 오류
arr2 = np.arange(5, 9).reshape(2, 2)
arr2

arr1 + arr2 # 각 요소별로 연산

arr1 + 3 # 모든 요소에 각각 3 연산

arr1 * arr2 # 각 요소 단위로 곱함

np.add(arr1, arr2) # 더하는 함수
np.subtract(arr1, arr2) # 빼기

array([[-4, -4],
       [-4, -4]])

In [31]:
arr1.dot(arr2) # 행렬 연산
# (x, y) 행렬이면 (y, z) 이어야 차원수가 맞음
# y가 맞아야 연산이 가능함, 에러의 대부분 차지

# (1*5 + 2*7) (1*6 + 2*8) # 식 계산

array([[19, 22],
       [43, 50]])

In [32]:
# 슬라이싱; 중요

arr = np.arange(1, 10).reshape(-1, 3) # 차원수가 뒤에서 부터 참
print(arr) # -1 은 축과는 무관, 만드는 방법

print(np.arange(1, 25).reshape(-1, 3, 4)) # 4가 0번축, 3이 1번축,
# 4개를 한줄로 3묶음을 만들고
# -1은 남는걸 알아서 정해줌

arr[:2, 1:3] # 2차원에서는 행이 0번 축, 열이 1번 축 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


array([[2, 3],
       [5, 6]])

In [33]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
arr[:2, 1:3]
# 1:3이 0번축의 범위
# :2는 1번축의 범위
# 두 범위의 교집합을 슬라이싱

# 슬라이싱한 배열은 원본 배열의 뷰
# 슬라이싱한 배열을 수정하면 원본 배열도 바뀜(py의 특징)
# 새로운 배열 생성은 copy(); 습관화 해야 원래 데이터 훼손 방지

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

In [34]:
arr1 = arr[:2, 1:3]
print(arr1)

arr1[1, 1] = 99
print(arr1)

#  원본 데이터 변경됨
print(arr)

[[2 3]
 [5 6]]
[[ 2  3]
 [ 5 99]]
[[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]]


In [35]:
# mutable vs immutable
# mut; 값이 변할 수 있는
# immut; 값이 변할 수 없는

In [36]:
print(arr[0, 2]) # 교차되는 범위
print(arr[[0, 1, 2], [2, 0, 1]])
# 2, 0, 1 은 0번 축의 내용
# 0, 1, 2 는 1번 축의 내용

3
[3 4 8]


In [37]:
# 배열 인덱싱

arr = np.arange(1, 7).reshape(2, 3)

print(arr > 3) # bool 값 출력

arr[arr> 3]
# 조건을 만족하는 데이터만 추출
# 배열이 흐트러짐
# np는 순서는 중요하지 않음

[[False False False]
 [ True  True  True]]


array([4, 5, 6])

In [38]:
idx = arr > 3
idx

arr[idx]

array([4, 5, 6])

## wine_quality 사례

In [39]:
import numpy as np
import pandas as pd

url_red = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
url_white = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv'
# https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality.names
# url_red = 'C:\jhpark\sync\python\db\winequality-red.csv'
# url_white = 'C:\jhpark\sync\python\db\winequality-white.csv'

# np 파일 읽어오는 함수
redwine = np.loadtxt(fname = url_red, delimiter = ';', skiprows = 1)
whitewine = np.loadtxt(fname = url_white, delimiter = ';', skiprows = 1)
# skiprows = 1; 첫줄 건너뛰기
# delimiter; 값을 구분하는 구분자 설정, 기본값은 \

print(redwine)
print(whitewine)

# pd로 읽는 법
print(pd.read_csv(url_red, delimiter = ';').values)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]
[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [40]:
# 통계 이야기

# 모수; 관심있는 데이터 전체 집합
# 샘플; 전체를 알 수 없어 부분을 추출하여 모수를 예측, 대표성을 어떤 지표에 둘 것인지
# 대표성 지표; 평균, 중앙값, 최빈값, 분산, 표준편차
# 최솟값, 최댓값을 기준으로 데이터 보정하여 비교할 때 이용

In [41]:
redwine.sum()
redwine.mean()
redwine.mean(axis = 0) # 0번 축에 대한 평균

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [42]:
arr = np.arange(1, 7).reshape(2, 3)
print(arr)
arr.sum()
arr.mean()
arr.mean(axis = 0)
arr.mean(axis = 1)

[[1 2 3]
 [4 5 6]]


array([2., 5.])

In [43]:
arr = np.arange(1, 13).reshape(2, 3, 2)
print(arr)
arr.sum()
arr.mean()
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))
print(arr.mean(axis = 2))
# 축 구분 중요

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[4. 5.]
 [6. 7.]
 [8. 9.]]
[[ 3.  4.]
 [ 9. 10.]]
[[ 1.5  3.5  5.5]
 [ 7.5  9.5 11.5]]


In [44]:
# 축에 따른 연산 구분
myarr = np.arange(1, 25).reshape(2, 3, 4)
print(myarr)

print(myarr.sum())
print(myarr.sum(axis = 0))
print(myarr.sum(axis = 1))
print(myarr.sum(axis = 2))

print(myarr.mean())
print(myarr.mean(axis = 0))
print(myarr.mean(axis = 1))
print(myarr.mean(axis = 2))

# https://acdongpgm.tistory.com/140
# https://ichi.pro/ko/numpy-indegsing-seolmyeong-214914454144013
# http://taewan.kim/post/numpy_cheat_sheet/
# https://velog.io/@kkiyou/ds1020
# https://laboputer.github.io/machine-learning/2020/04/25/numpy-quickstart/

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
300
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[15 18 21 24]
 [51 54 57 60]]
[[10 26 42]
 [58 74 90]]
12.5
[[ 7.  8.  9. 10.]
 [11. 12. 13. 14.]
 [15. 16. 17. 18.]]
[[ 5.  6.  7.  8.]
 [17. 18. 19. 20.]]
[[ 2.5  6.5 10.5]
 [14.5 18.5 22.5]]


In [45]:
redwine[:, 0]
redwine[:, 0].mean()

8.31963727329581

## pandas 10 min

https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html#minutes-to-pandas
https://dataitgirls2.github.io/tutorial/Tutorial_180717_10minPandas.html

In [46]:
# 라이브러리 사용
import numpy as np
import pandas as pd

In [47]:
# 사용 라이브러리 버전
print('numpy ver =', np.__version__)
print('pandas ver =', pd.__version__)

numpy ver = 1.20.1
pandas ver = 1.2.4


In [48]:
# object creation; 객체 생성
s = pd.Series([1, 3, 5, np.nan, 6, 8])
# np.nan; null 값
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [49]:
dates = pd.date_range('20130101', periods=6, freq='d')
# 일별로 날짜 데이터 불러오기
# w 주, m 월별

dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [50]:
df = pd.DataFrame(np.random.randn(6, 4),
                  index=dates,
                  columns=list('ABCD') # ['A', 'B', 'C', 'D']
                 )
df

A         B         C         D
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-03 -0.535101  0.782207  1.244994 -0.500447
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498
2013-01-06 -0.740786  0.325351 -0.097022  0.395777

In [51]:
np.random.seed()
# 난수를 고정시켜 주기 위해
# 순서도 seed, randn 지켜주어야 고정됨
# 123은 아무 숫자
np.random.randn(6, 4)
# 6행4열 난수 생성
# 평균이 0, 분산이 1인 데이터

array([[-4.17572123e-01, -1.42805885e+00, -1.20665052e+00,
         8.86356396e-01],
       [-2.22618866e-01,  2.63123000e+00, -4.78460354e-01,
        -6.87314015e-01],
       [ 6.66686414e-01, -5.87376541e-01,  1.45010383e+00,
         7.07153378e-01],
       [ 2.03711810e-01,  5.68313981e-01,  4.60611207e-01,
         9.97011335e-01],
       [ 2.99415548e-01, -1.03721169e+00, -1.25378605e-01,
        -9.10553726e-01],
       [-2.07360956e-03,  1.16475183e-01,  1.16445707e+00,
        -6.26966748e-01]])

In [52]:
df2 = pd.DataFrame({'A': 1.0,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(['test', 'train', 'test', 'train']),
                    'F': 'foo'
                   })

df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [53]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32       
 3   D       4 non-null      int32         
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 288.0+ bytes


In [54]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [55]:
# viewing data; 데이터 조회

df.head()
df.tail()
df.index
df.columns
df.columns = list('ABCD') # 컬럼명 수정
df

A         B         C         D
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-03 -0.535101  0.782207  1.244994 -0.500447
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498
2013-01-06 -0.740786  0.325351 -0.097022  0.395777

In [56]:
# tmp

In [57]:
df.to_numpy()

array([[-1.68772597, -0.39633456,  0.39929248, -0.02077358],
       [-0.50484076,  0.49494235,  0.76377549,  0.7246021 ],
       [-0.53510144,  0.78220713,  1.24499373, -0.50044655],
       [-1.03992083, -0.37044067, -0.15787486,  0.03931251],
       [-2.32329336,  0.93247151, -0.16570449, -0.57849838],
       [-0.74078579,  0.3253514 , -0.09702206,  0.39577669]])

In [58]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [59]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -1.138611  0.294700  0.331243  0.009995
std    0.726484  0.566638  0.582453  0.503621
min   -2.323293 -0.396335 -0.165704 -0.578498
25%   -1.525775 -0.196493 -0.142662 -0.380528
50%   -0.890353  0.410147  0.151135  0.009269
75%   -0.586523  0.710391  0.672655  0.306661
max   -0.504841  0.932472  1.244994  0.724602

In [60]:
df.T # 행과 열을 바꿈

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.687726   -0.504841   -0.535101   -1.039921   -2.323293   -0.740786
B   -0.396335    0.494942    0.782207   -0.370441    0.932472    0.325351
C    0.399292    0.763775    1.244994   -0.157875   -0.165704   -0.097022
D   -0.020774    0.724602   -0.500447    0.039313   -0.578498    0.395777

In [61]:
df.sort_index()

A         B         C         D
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-03 -0.535101  0.782207  1.244994 -0.500447
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498
2013-01-06 -0.740786  0.325351 -0.097022  0.395777

In [62]:
df.sort_index(ascending=False)

A         B         C         D
2013-01-06 -0.740786  0.325351 -0.097022  0.395777
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313
2013-01-03 -0.535101  0.782207  1.244994 -0.500447
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774

In [63]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01 -0.020774  0.399292 -0.396335 -1.687726
2013-01-02  0.724602  0.763775  0.494942 -0.504841
2013-01-03 -0.500447  1.244994  0.782207 -0.535101
2013-01-04  0.039313 -0.157875 -0.370441 -1.039921
2013-01-05 -0.578498 -0.165704  0.932472 -2.323293
2013-01-06  0.395777 -0.097022  0.325351 -0.740786

In [64]:
df[['D', 'C', 'B', 'A']]

D         C         B         A
2013-01-01 -0.020774  0.399292 -0.396335 -1.687726
2013-01-02  0.724602  0.763775  0.494942 -0.504841
2013-01-03 -0.500447  1.244994  0.782207 -0.535101
2013-01-04  0.039313 -0.157875 -0.370441 -1.039921
2013-01-05 -0.578498 -0.165704  0.932472 -2.323293
2013-01-06  0.395777 -0.097022  0.325351 -0.740786

In [65]:
df.sort_values(by='B', ascending=False)

A         B         C         D
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498
2013-01-03 -0.535101  0.782207  1.244994 -0.500447
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-06 -0.740786  0.325351 -0.097022  0.395777
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774

## selection; 데이터 추출

df.loc, df.iloc, df.at, df.iat

In [66]:
df['A']

2013-01-01   -1.687726
2013-01-02   -0.504841
2013-01-03   -0.535101
2013-01-04   -1.039921
2013-01-05   -2.323293
2013-01-06   -0.740786
Freq: D, Name: A, dtype: float64

In [67]:
df[0:3]

A         B         C         D
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-03 -0.535101  0.782207  1.244994 -0.500447

In [68]:
# df['20130102':'20130104'] # 날짜형이지만 문자열처럼 인식 가능
# df[''] # - 를 넣어도, 빼도 됨

In [69]:
# selection by label; loc
df.loc[dates[0]]
# 인덱스가 컬럼이 되어서 가져옴

A   -1.687726
B   -0.396335
C    0.399292
D   -0.020774
Name: 2013-01-01 00:00:00, dtype: float64

In [70]:
dates[0]

Timestamp('2013-01-01 00:00:00', freq='D')

In [71]:
df.loc[:, ['A', 'B']] # 멀티인덱스

A         B
2013-01-01 -1.687726 -0.396335
2013-01-02 -0.504841  0.494942
2013-01-03 -0.535101  0.782207
2013-01-04 -1.039921 -0.370441
2013-01-05 -2.323293  0.932472
2013-01-06 -0.740786  0.325351

In [72]:
df.loc['20130102':'20130104', ['A', 'B']]
# 인덱스 값을 알 때 레이블로 가져옴

A         B
2013-01-02 -0.504841  0.494942
2013-01-03 -0.535101  0.782207
2013-01-04 -1.039921 -0.370441

In [73]:
df.loc['20130102', ['A', 'B']]

A   -0.504841
B    0.494942
Name: 2013-01-02 00:00:00, dtype: float64

In [74]:
# 한개의 스칼라 데이터
df.loc[dates[0], 'A']

-1.6877259658991006

In [75]:
df.at[dates[0], 'A']

-1.6877259658991006

In [76]:
# selection by position; iloc
df

A         B         C         D
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774
2013-01-02 -0.504841  0.494942  0.763775  0.724602
2013-01-03 -0.535101  0.782207  1.244994 -0.500447
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498
2013-01-06 -0.740786  0.325351 -0.097022  0.395777

In [77]:
df.iloc[3] # 인덱스3 행

A   -1.039921
B   -0.370441
C   -0.157875
D    0.039313
Name: 2013-01-04 00:00:00, dtype: float64

In [78]:
# loc와 iloc 차이는
# iloc 컬럼 숫자, loc 컬럼명, 거의 비슷함

In [79]:
df.iloc[1, 1]

0.49494234911866075

In [80]:
df.iat[1, 1]

0.49494234911866075

In [81]:
# bool indexing
df['A'] > 0

2013-01-01    False
2013-01-02    False
2013-01-03    False
2013-01-04    False
2013-01-05    False
2013-01-06    False
Freq: D, Name: A, dtype: bool

In [82]:
df[df['A'] > 0.6] # 조건에 맞는 전체 데이터 추출

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [83]:
df2 = df.copy() # 원본데이터 유지
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three'] # 컬럼 추가
df2

A         B         C         D      E
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774    one
2013-01-02 -0.504841  0.494942  0.763775  0.724602    one
2013-01-03 -0.535101  0.782207  1.244994 -0.500447    two
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313  three
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498   four
2013-01-06 -0.740786  0.325351 -0.097022  0.395777  three

In [84]:
e = ['one', 'one', 'two', 'three', 'four', 'three']
df2['E'] = e
df2

A         B         C         D      E
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774    one
2013-01-02 -0.504841  0.494942  0.763775  0.724602    one
2013-01-03 -0.535101  0.782207  1.244994 -0.500447    two
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313  three
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498   four
2013-01-06 -0.740786  0.325351 -0.097022  0.395777  three

In [85]:
df2['E'].isin(['two', 'four']) # 리스트 형태 받음

2013-01-01    False
2013-01-02    False
2013-01-03     True
2013-01-04    False
2013-01-05     True
2013-01-06    False
Freq: D, Name: E, dtype: bool

In [86]:
df2[df2['E'].isin(['two', 'four'])] # 전체 데이터 출력

A         B         C         D     E
2013-01-03 -0.535101  0.782207  1.244994 -0.500447   two
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498  four

In [87]:
# setting; 값 변경
s1 = pd.Series([1, 2, 3, 4, 5, 6],
               index=pd.date_range('20130102', periods=6)
              )
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [88]:
df['F'] = s1
df

A         B         C         D    F
2013-01-01 -1.687726 -0.396335  0.399292 -0.020774  NaN
2013-01-02 -0.504841  0.494942  0.763775  0.724602  1.0
2013-01-03 -0.535101  0.782207  1.244994 -0.500447  2.0
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313  3.0
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498  4.0
2013-01-06 -0.740786  0.325351 -0.097022  0.395777  5.0

In [89]:
df.at[dates[0], 'A']

-1.6877259658991006

In [90]:
df.loc[dates[0], 'A'] = 0 # df.at 과 같음
# 위치 지정
df

A         B         C         D    F
2013-01-01  0.000000 -0.396335  0.399292 -0.020774  NaN
2013-01-02 -0.504841  0.494942  0.763775  0.724602  1.0
2013-01-03 -0.535101  0.782207  1.244994 -0.500447  2.0
2013-01-04 -1.039921 -0.370441 -0.157875  0.039313  3.0
2013-01-05 -2.323293  0.932472 -0.165704 -0.578498  4.0
2013-01-06 -0.740786  0.325351 -0.097022  0.395777  5.0

In [91]:
df.loc[:, 'D']

2013-01-01   -0.020774
2013-01-02    0.724602
2013-01-03   -0.500447
2013-01-04    0.039313
2013-01-05   -0.578498
2013-01-06    0.395777
Freq: D, Name: D, dtype: float64

In [92]:
np.array([5] * len(df)) # 이 형태의 데이터 추가

df.loc[:, 'D'] = np.array([5] * len(df))
df

A         B         C  D    F
2013-01-01  0.000000 -0.396335  0.399292  5  NaN
2013-01-02 -0.504841  0.494942  0.763775  5  1.0
2013-01-03 -0.535101  0.782207  1.244994  5  2.0
2013-01-04 -1.039921 -0.370441 -0.157875  5  3.0
2013-01-05 -2.323293  0.932472 -0.165704  5  4.0
2013-01-06 -0.740786  0.325351 -0.097022  5  5.0

In [93]:
df2 = df.copy()
df2[df2 > 0]
-df2
df2[df2 > 0] = -df2 # - 값으로 추가
df2

A         B         C  D    F
2013-01-01  0.000000 -0.396335 -0.399292 -5  NaN
2013-01-02 -0.504841 -0.494942 -0.763775 -5 -1.0
2013-01-03 -0.535101 -0.782207 -1.244994 -5 -2.0
2013-01-04 -1.039921 -0.370441 -0.157875 -5 -3.0
2013-01-05 -2.323293 -0.932472 -0.165704 -5 -4.0
2013-01-06 -0.740786 -0.325351 -0.097022 -5 -5.0

In [94]:
# missing data; 결측치 찾기 중요, 채워서 사용
df1 = df.reindex(index=dates[0:4],
                 columns=list(df.columns) + ['E']
                )
df1

A         B         C  D    F   E
2013-01-01  0.000000 -0.396335  0.399292  5  NaN NaN
2013-01-02 -0.504841  0.494942  0.763775  5  1.0 NaN
2013-01-03 -0.535101  0.782207  1.244994  5  2.0 NaN
2013-01-04 -1.039921 -0.370441 -0.157875  5  3.0 NaN

In [95]:
df1.loc[dates[0]:dates[1], 'E'] = 1 # 1 추가
df1

A         B         C  D    F    E
2013-01-01  0.000000 -0.396335  0.399292  5  NaN  1.0
2013-01-02 -0.504841  0.494942  0.763775  5  1.0  1.0
2013-01-03 -0.535101  0.782207  1.244994  5  2.0  NaN
2013-01-04 -1.039921 -0.370441 -0.157875  5  3.0  NaN

In [96]:
df1.dropna(how='all')
# null 값 있다면 drop
# how =  any 하나라도, all 모두
# 보통 all 사용

A         B         C  D    F    E
2013-01-01  0.000000 -0.396335  0.399292  5  NaN  1.0
2013-01-02 -0.504841  0.494942  0.763775  5  1.0  1.0
2013-01-03 -0.535101  0.782207  1.244994  5  2.0  NaN
2013-01-04 -1.039921 -0.370441 -0.157875  5  3.0  NaN

In [97]:
df1.fillna(value = 5) # inplace 로 수정 확인
df1 # 채우는 부분은 다양한 수식 가능

A         B         C  D    F    E
2013-01-01  0.000000 -0.396335  0.399292  5  NaN  1.0
2013-01-02 -0.504841  0.494942  0.763775  5  1.0  1.0
2013-01-03 -0.535101  0.782207  1.244994  5  2.0  NaN
2013-01-04 -1.039921 -0.370441 -0.157875  5  3.0  NaN

In [98]:
# operations; 연산자
df.mean()

A   -0.857324
B    0.294700
C    0.331243
D    5.000000
F    3.000000
dtype: float64

In [99]:
df.mean(axis=1)

2013-01-01    1.250739
2013-01-02    1.350775
2013-01-03    1.698420
2013-01-04    1.286353
2013-01-05    1.488695
2013-01-06    1.897509
Freq: D, dtype: float64

In [100]:
s = pd.Series([1, 3, 5, np.nan, 6, 8],
              index=dates.shift(2) # 밑으로 2개식 미룸, 날짜 연산시 활용
             )
s

2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
2013-01-07    6.0
2013-01-08    8.0
Freq: D, dtype: float64

In [101]:
df.sub(s, axis='index') # 인덱스 기준으로 s를 빼는 연산

A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -1.535101 -0.217793  0.244994  4.0  1.0
2013-01-04 -4.039921 -3.370441 -3.157875  2.0  0.0
2013-01-05 -7.323293 -4.067528 -5.165704  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN
2013-01-07       NaN       NaN       NaN  NaN  NaN
2013-01-08       NaN       NaN       NaN  NaN  NaN

In [102]:
# apply
df.apply(np.cumsum) # 각행에 동일하게 적용, cumsum은 누적합, apply는 모든 열에 동일하게

A         B         C   D     F
2013-01-01  0.000000 -0.396335  0.399292   5   NaN
2013-01-02 -0.504841  0.098608  1.163068  10   1.0
2013-01-03 -1.039942  0.880815  2.408062  15   3.0
2013-01-04 -2.079863  0.510374  2.250187  20   6.0
2013-01-05 -4.403156  1.442846  2.084482  25  10.0
2013-01-06 -5.143942  1.768197  1.987460  30  15.0

In [103]:
df.apply(lambda x: x.max() - x.min()) # 이름 없이 그냥 실행하는 함수 람다
# 컬럼의 최댓값과 최솟값의 차이를 구해서 각 컬럼마다

A    2.323293
B    1.328806
C    1.410698
D    0.000000
F    4.000000
dtype: float64

In [104]:
# 히스토그래밍
s = pd.Series(np.random.randint(0, 7, size=10))
s.value_counts()

1    3
6    2
0    1
2    1
3    1
4    1
5    1
dtype: int64

명령어, 함수를 모두 알아서 구현하기는 어려움

눈으로라도 확인하고 지나가보기

1. 기초명령어, 함수는 필수만 암기; 10~15개
2. 그 외에는 함수의 기능을 기억해서 검색해서 이용; 30개
3. 찾고자하는, 구현하고자 하는 기능을 생각해서 함수 검색

In [105]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca",
               np.nan, "CABA", "dog", "cat"])
# 모든 데이터 소문자화
# srs 데이터를 먼저 문자열로 바꾸고 소문자화
s.str.lower()

# 앞의 한 자씩은
s.str.title()

0       A
1       B
2       C
3    Aaba
4    Baca
5     NaN
6    Caba
7     Dog
8     Cat
dtype: object

In [106]:
# merge
df1 = pd.DataFrame({"A": ["A0", "A1", "A2", "A3"],
                    "B": ["B0", "B1", "B2", "B3"],
                    "C": ["C0", "C1", "C2", "C3"],
                    "D": ["D0", "D1", "D2", "D3"],
                   },
                   index=[0, 1, 2, 3],
                  )

df2 = pd.DataFrame({"A": ["A4", "A5", "A6", "A7"],
                    "B": ["B4", "B5", "B6", "B7"],
                    "C": ["C4", "C5", "C6", "C7"],
                    "D": ["D4", "D5", "D6", "D7"],
                   },
                   index=[4, 5, 6, 7],
                  )

df3 = pd.DataFrame({"A": ["A8", "A9", "A10", "A11"],
                    "B": ["B8", "B9", "B10", "B11"],
                    "C": ["C8", "C9", "C10", "C11"],
                    "D": ["D8", "D9", "D10", "D11"],
                   },
                   index=[8, 9, 10, 11],
                  )

pd.concat([df1, df2])
# 누적된 df를 만듦. 같은 컬럼

pd.concat([df2, df1], ignore_index=True)
# 원래 인덱스를 무시하고, 자신만의 새로운 인덱스 구성

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7
4  A0  B0  C0  D0
5  A1  B1  C1  D1
6  A2  B2  C2  D2
7  A3  B3  C3  D3

In [107]:
pd.concat([df2, df1], axis=1)
# 인덱스가 같으면 옆으로 붙음
# 다르면 알아서 붙음

A    B    C    D    A    B    C    D
0  NaN  NaN  NaN  NaN   A0   B0   C0   D0
1  NaN  NaN  NaN  NaN   A1   B1   C1   D1
2  NaN  NaN  NaN  NaN   A2   B2   C2   D2
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3
4   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   A7   B7   C7   D7  NaN  NaN  NaN  NaN

In [108]:
# append
df1.append(df2)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [109]:
df2.append(df1)

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [110]:
# concat 쓸 때, join='inner' 추가해서 sql처럼 사용가능
# 키 별로 머지하는 방법
# join 부분도 확인
# grouping

df = pd.DataFrame({"A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
                   "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
                   "C": np.random.randn(8),
                   "D": np.random.randn(8),
                  }
                 )
list(df.groupby('A'))

[('bar',
       A      B         C         D
  1  bar    one  1.096781 -0.654049
  3  bar  three -0.546403  0.425482
  5  bar    two -0.990182  1.184147),
 ('foo',
       A      B         C         D
  0  foo    one  0.064285 -1.219804
  2  foo    two -1.065989 -1.160332
  4  foo    two -1.360883 -0.305803
  6  foo    one  2.324746 -0.050006
  7  foo  three -0.426589 -0.272527)]

In [111]:
df.groupby('A').sum()

C         D
A                      
bar -0.439804  0.955580
foo -0.464430 -3.008472

In [112]:
df.groupby(['A', 'B']).sum()

C         D
A   B                        
bar one    1.096781 -0.654049
    three -0.546403  0.425482
    two   -0.990182  1.184147
foo one    2.389032 -1.269810
    three -0.426589 -0.272527
    two   -2.426872 -1.466136

In [113]:
# reshaping; 자습
# 라벨 준 만큼 컬럼을 바꿈
# 데이터 구조를 수정
# 스택과 언스택
# 언스택시 1을 주면, 0이면 다른 방식으로 바꿈

# pivot

# time series 시계열 데이터 처리에는 중요
# 시간 관련 함수 기능 제공

# catego 그룹화

# plotting; 맷플 기능 이전에 기본적 시각화 가능

# csv 읽기, 저장하기

# 엑셀파일도 가능

# pd10m은 타이틀 위주로 기억해서 찾아 쓸 수 있도록