In [1]:
# https://laboputer.github.io/machine-learning/2020/04/25/numpy-quickstart/

## 기초 개념

In [2]:
import numpy as np

In [3]:
[[1, 0, 0],
 [0, 1, 2]]

[[1, 0, 0], [0, 1, 2]]

In [6]:
a = np.arange(15).reshape(3,5) ; a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a.shape  #축의 크기

(3, 5)

In [19]:
a.ndim  #축의 개수

2

In [20]:
a.dtype  #각 요소의 타입

dtype('int32')

In [21]:
a.itemsize  #각 요소의 타입의 bytes크기

4

In [22]:
a.size  #전체 요소의 개수

15

In [24]:
type(a)

numpy.ndarray

배열 생성하기

In [26]:
a = np.array([2,3,4])
print(a)

[2 3 4]


In [28]:
a.dtype

dtype('int32')

In [31]:
b = np.array([1.2, 3.5, 5.1])
print(b)

[1.2 3.5 5.1]


In [33]:
b.dtype

dtype('float64')

In [50]:
b = np.array([(1.5, 2, 3), (4, 5, 6)]) # = ([[1.5, 2, 3], [4, 5, 6]])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [51]:
b.dtype

dtype('float64')

In [53]:
#복소수 값 생성
c = np.array([(1, 2), (3, 4)], dtype = complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [58]:
np.zeros((3,4))  #0으로 구성된 배열 생성

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones((3,4), dtype = np.int32)  #1로 구성된 배열 생성

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [64]:
np.empty((2,3), dtype = np.int16) #초기화 되지 않은 배열 생성

array([[257, 257, 257],
       [257, 257, 257]], dtype=int16)

- np.arange()
- np.linspace()

In [66]:
np.arange(10, 30, 5) #10이상 30미만 까지 5씩 차이나게 생성

array([10, 15, 20, 25])

In [68]:
np.linspace(0,99,100) #0~99까지 100등분

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

In [70]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [74]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [77]:
np.arange(12).reshape(2,2,3) # 3D 배열은 2차원이 reshape[0]개 출력

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

기본연산

In [80]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [82]:
c = a - b
c

array([20, 29, 38, 47])

In [84]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [88]:
np.sin(a)*10  #각각의 원소에 *10 연산

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [89]:
print(a<35)  #boolean 결과

[ True  True False False]


- * 각각의 원소끼리 곱셈
- @ 행렬 곱셈
- .dot() 행렬 내적

In [93]:
a = np.array([[1,1], [0,1]])
print(a)

[[1 1]
 [0 1]]


In [96]:
b = np.array([[2,0], [3,4]])
print(b)

[[2 0]
 [3 4]]


In [97]:
a*b  # 각각의 원소끼리 곱셈

array([[2, 0],
       [0, 4]])

In [99]:
a@b  # 행렬 곱셈

array([[5, 4],
       [3, 4]])

In [101]:
a.dot(b) #행렬 내적

array([[5, 4],
       [3, 4]])

In [109]:
#원소 각각의 타입이 다르면 큰 쪽(int < float < complex(복소수))으로 자동 변경
a = np.ones(3, dtype = np.int32)
a

array([1, 1, 1])

In [111]:
b = np.linspace(0, np.pi, 3)
b

array([0.        , 1.57079633, 3.14159265])

In [115]:
b.dtype.name

'float64'

In [121]:
d = np.exp(c*1j) # 밑이 자연상수 e인 지수함수(e^x)로 변환
d

array([ 0.40808206+0.91294525j, -0.74805753-0.66363388j,
        0.95507364+0.29636858j, -0.99233547+0.12357312j])

In [123]:
d.dtype

dtype('complex128')

In [126]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [128]:
a = a**2
a

array([[   0,    1,   16,   81],
       [ 256,  625, 1296, 2401]], dtype=int32)

In [129]:
a.sum() #모든 요소의 합

4676

In [130]:
a.min()

0

In [132]:
a.max()

2401

In [134]:
a.argmax() #최대값의 인덱스

7

In [135]:
a.cumsum() #모든 요소의 누적합

array([   0,    1,   17,   98,  354,  979, 2275, 4676], dtype=int32)

In [140]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
b.sum(axis = 0) #열

array([12, 15, 18, 21])

In [144]:
b.sum(axis = 1) #행

array([ 6, 22, 38])

In [146]:
B = np.arange(3) ; B

array([0, 1, 2])

In [147]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [148]:
np.sqrt(B)  #제곱근

array([0.        , 1.        , 1.41421356])

In [156]:
a = np.arange(10) ; a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
a = a**3

In [159]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [161]:
a[0:5]

array([ 0,  1,  8, 27, 64], dtype=int32)

In [163]:
a[:6:2]  #0~5번에서 2step 인덱스

array([ 0,  8, 64], dtype=int32)

In [167]:
a[:6:2] = 1000 #0~5번에서 2step마다 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [169]:
a[: :-1] #reverse 거꾸로 뒤집기

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [ ]:
#np.fromfunction()를 통해 인덱스 번호를 가지고 함수를 정의해 생성할 수 있음

In [177]:
def f(x,y):
    return (10*x)+y

In [179]:
b = np.fromfunction(f, (5,4), dtype=int) ; b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [180]:
b[2,3]

23

In [181]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [183]:
b[:, 1]

array([ 1, 11, 21, 31, 41])

In [185]:
b[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [187]:
b[-1]

array([40, 41, 42, 43])

x가 5차원 일때
- x[1,2,...] = x[1,2,:,:,:]

In [193]:
c = np.array([[[0, 1, 2], [10, 12, 13]], [[100, 101, 102], [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [194]:
c.shape

(2, 2, 3)

In [196]:
c[1,...] 

array([[100, 101, 102],
       [110, 112, 113]])

In [198]:
c[1,:,:]

array([[100, 101, 102],
       [110, 112, 113]])

In [200]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [201]:
c[:, :, 2]

array([[  2,  13],
       [102, 113]])

In [202]:
#다차원 배열의 for문은 axis=0 기준으로 적용
#다차원 배열에 for문을 적용할 경우 .reshape .flat 둘 다 가능

'다차원 배열의 for문은 axis=0 기준으로 적용\n다차원 배열에 for문을 적용할 경우 .reshape .flat 둘 다 가능'

In [207]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [214]:
list(b.flat)

[0, 1, 2, 3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40, 41, 42, 43]

In [217]:
b.reshape(1,20)

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33,
        40, 41, 42, 43]])

In [222]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [223]:
for element in b.reshape(1,20):
    print(element)

[ 0  1  2  3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43]


## Shape 변경

In [30]:
import numpy as np
import numpy.random as npr
a = np.floor(10*np.random.random((3,4))) # 10*npr.ramdom((3,4))
a

array([[6., 2., 1., 4.],
       [7., 6., 7., 0.],
       [0., 8., 2., 2.]])

In [15]:
a.shape

(3, 4)

In [17]:
a.ravel() #모든 원소를 1차원으로 변경

array([8., 5., 5., 6., 7., 6., 3., 8., 7., 9., 5., 5.])

In [18]:
a.reshape(2,6)

array([[8., 5., 5., 6., 7., 6.],
       [3., 8., 7., 9., 5., 5.]])

In [19]:
a.T  #[3,4]의 전치변환으로 [4,3]

array([[8., 7., 7.],
       [5., 6., 9.],
       [5., 3., 5.],
       [6., 8., 5.]])

In [21]:
a.T.shape

(4, 3)

In [23]:
print(a)

[[8. 5. 5. 6.]
 [7. 6. 3. 8.]
 [7. 9. 5. 5.]]


In [25]:
a.resize(2,6) ;a

array([[8., 5., 5., 6., 7., 6.],
       [3., 8., 7., 9., 5., 5.]])

In [26]:
a.reshape(3,-1)

array([[8., 5., 5., 6.],
       [7., 6., 3., 8.],
       [7., 9., 5., 5.]])

In [27]:
a #resize 원본 데이터 자체를 변경

array([[8., 5., 5., 6., 7., 6.],
       [3., 8., 7., 9., 5., 5.]])

In [32]:
a = np.floor(10*npr.random((2,2))) #np.floor(a) 작거나 같은 가장 큰 정수 값
a

array([[3., 2.],
       [4., 9.]])

In [33]:
b = np.floor(10*npr.random((2,2))) ;b

array([[7., 5.],
       [0., 0.]])

In [34]:
np.vstack((a,b)) #np.vstack() aixs = 0 기준으로 데이터 합

array([[3., 2.],
       [4., 9.],
       [7., 5.],
       [0., 0.]])

In [35]:
np.hstack((a,b)) #axis = 1 

array([[3., 2., 7., 5.],
       [4., 9., 0., 0.]])

In [39]:
a = np.floor(10*npr.random((2,12)))
a

array([[5., 7., 0., 2., 9., 3., 4., 1., 3., 2., 0., 5.],
       [9., 3., 8., 9., 3., 9., 4., 0., 1., 3., 4., 2.]])

In [40]:
np.hsplit(a,3)  #np.hsplit() 숫자 1개 들어갈 경우 X개로 등분,
                #리스트로 넣을 경우 axis=1 기준으로 분할

[array([[5., 7., 0., 2.],
        [9., 3., 8., 9.]]),
 array([[9., 3., 4., 1.],
        [3., 9., 4., 0.]]),
 array([[3., 2., 0., 5.],
        [1., 3., 4., 2.]])]

In [41]:
np.hsplit(a, (3,4))   #[:, :3], [:, 3:4], [:, 4:]로 분할

[array([[5., 7., 0.],
        [9., 3., 8.]]),
 array([[2.],
        [9.]]),
 array([[9., 3., 4., 1., 3., 2., 0., 5.],
        [3., 9., 4., 0., 1., 3., 4., 2.]])]

In [67]:
a = np.array([[0,1,2,3,], [4,5,6,7], [8,9,10,11]]) ;a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
b = a

In [45]:
b is a

True

In [46]:
id(b)

1919843132976

In [47]:
id(a)

1919843132976

In [77]:
c = a.view() ;c   #데이터 각각의 참조값을 복사

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
c is a

False

In [69]:
c.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [70]:
a.shape

(3, 4)

In [71]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
c[1, 0] = 1234 ; c

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [82]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [83]:
s = a[:, 1:3]

In [84]:
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [85]:
s[:] = 10

In [87]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [88]:
c

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [89]:
id(c)

1919843948848

In [90]:
id(a)

1919843948752

In [91]:
d = a.copy() ; d  #참조값 뿐만 아니라 데이터 전부가 새로운 객체로 생성 

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [92]:
d is a

False

In [93]:
id(d)

1919843413136

In [94]:
id(a)

1919843948752

In [95]:
d[0,0] = 9999; d

array([[9999,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [96]:
a       #참조값이 다름

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [98]:
a = np.arange(int(1e8)) ; a

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [100]:
b = a[:100].copy() ; b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [101]:
del a ; a

NameError: name 'a' is not defined

## 브로드캐스팅

In [102]:
np.array([1,2,3,4,5]) * 2

array([ 2,  4,  6,  8, 10])

In [103]:
np.array([1,2,3,4,5]) * np.array([2,2,2,2,2])

array([ 2,  4,  6,  8, 10])

In [ ]:
#차원(ndim)이 같고 축(axis)의 값이 같거나 1이여야 연산이 가능

In [104]:
np.arange(4) * 2

array([0, 2, 4, 6])

In [105]:
np.ones((3,4)) * np.arange(4)

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [111]:
np.arange(3).reshape((3,1)) * np.arange(3)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## 인덱싱

In [114]:
a = np.arange(12)**2 ; a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [116]:
i = np.array([1, 1, 3, 8, 5]) ; i

array([1, 1, 3, 8, 5])

In [117]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [118]:
j = np.array([[3,4], [9,7]]); j

array([[3, 4],
       [9, 7]])

In [119]:
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [121]:
palette = np.array([[0,0,0], [255, 0, 0], [0, 255, 0],
                   [0, 0, 255], [255, 255, 255]])
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [123]:
image = np.array([[0, 1, 2, 0], [0, 3, 4, 0]])
image

array([[0, 1, 2, 0],
       [0, 3, 4, 0]])

In [124]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [126]:
a = np.arange(5) ; a

array([0, 1, 2, 3, 4])

In [127]:
a[[1, 3, 4]] = 0; a

array([0, 0, 2, 0, 0])

In [128]:
a = np.arange(5) ; a

array([0, 1, 2, 3, 4])

In [129]:
a[[0, 0, 2]] += 1 ; a

array([1, 1, 3, 3, 4])

In [ ]:
#bool타입의 값으로 인덱싱

In [134]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
b = a > 4 ; b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [135]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [136]:
a[b] = 0

In [138]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [140]:
a = np.array([2, 3, 4, 5])
b = np.array([8, 5, 4])
c = np.array([5, 4, 6, 8, 3])
ax, bx, cx = np.ix_(a,b,c) #다른 shape을 가진 배열들을 묶음

In [141]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [143]:
bx

array([[[8],
        [5],
        [4]]])

In [144]:
cx

array([[[5, 4, 6, 8, 3]]])

In [146]:
ax.shape

(4, 1, 1)

In [148]:
bx.shape

(1, 3, 1)

In [150]:
cx.shape

(1, 1, 5)

In [151]:
result = ax+bx*cx

In [153]:
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [155]:
result[3, 2, 4]

17

In [158]:
a[3]+b[2]*c[4]

17

## 선형대수