In [1]:
import pandas  as pd
import numpy as np

In [239]:
df = pd.read_csv("./Quiz2/X_test.csv")

* [이전 기출문제]'내점일수'가 90인 값을 '내점일수' 중앙값(median)으로 바꾸고    
변경전, 변경 후 '내점일수'의 표준편차 출력


In [240]:
before = df['내점일수'].std()
before

idx = df[df['내점일수'] == 90].index  #[1, 501, 529, 1217]
df.loc[idx , '내점일수']  = df['내점일수'].median()  #19.516921837228043

after = df['내점일수'].std()
# print(before, after)   #25.97397225487153 25.81907960953315
print(before - after)    #0.15489264533837854



0.15151968516001801


In [207]:
print(df.columns.tolist())
df.head(2)

['cust_id', '총구매액', '최대구매액', '환불금액', '주구매상품', '주구매지점', '내점일수', '내점당구매건수', '주말방문비율', '구매주기']


cust_id       총구매액     최대구매액        환불금액 주구매상품 주구매지점  내점일수   내점당구매건수  \
0     3500   70900400  22000000   4050000.0    골프  부산본점    13  1.461538   
1     3501  310533100  38558000  48034700.0   농산물   잠실점    90  2.433333   

     주말방문비율  구매주기  
0  0.789474    26  
1  0.369863     3

In [221]:
df = df.sort_values(by='구매주기', ascending=False)[:10]
idx = df.index
df.loc[idx[9], '구매주기'] 
df.loc[idx, '구매주기'] = 139
df.head()

#for idx in df['구매주기'].sort_values(ascending =False)[:10].index:
#    df.loc[idx, '구매주기'] =  df.loc[2026, '구매주기']



cust_id      총구매액     최대구매액  환불금액  주구매상품 주구매지점  내점일수  내점당구매건수    주말방문비율  \
1693     5193  16259600  10830000   NaN  모피/피혁   잠실점     2      1.5  0.333333   
1549     5049   2787000   2556000   NaN   건강식품   일산점     2      1.0  0.000000   
1034     4534   2775000   2625000   NaN     구두   잠실점     2      1.0  0.500000   
1430     4930  11465000  10010000   NaN   생활잡화   노원점     2      1.5  0.000000   
1393     4893   1339100    931000   NaN    캐주얼  영등포점     2      2.0  0.500000   

      구매주기  
1693   139  
1549   139  
1034   139  
1430   139  
1393   139

* [QUIZ]주구매상품이 스포츠이거나 캐주얼인 경우 구매주기 평균

In [15]:
print(df[(df['주구매상품']=='스포츠') | (df['주구매상품']=='캐주얼')]['구매주기'].mean())
res = df[(df['주구매상품']=='스포츠') | (df['주구매상품']=='캐주얼')]['구매주기'].mean()
print(res)

22.02777777777778
22.02777777777778


In [11]:
df['주구매상품'].unique()

array(['골프', '농산물', '가공식품', '주방용품', '수산품', '화장품', '기타', '스포츠', '디자이너',
       '시티웨어', '구두', '캐주얼', '명품', '건강식품', '남성정장', '커리어', '남성 캐주얼', '축산가공',
       '식기', '피혁잡화', '모피/피혁', '섬유잡화', '트래디셔널', '차/커피', '육류', '가구', '아동',
       '셔츠', '액세서리', '젓갈/반찬', '대형가전', '일용잡화', '통신/컴퓨터', '생활잡화', '주방가전',
       '란제리/내의', '남성 트랜디', '보석', '주류', '침구/수예', '악기'], dtype=object)

* [QUIZ]총구매액이 80000000 이상인 고객의 평균 구매금액

In [19]:
print(df[df['총구매액'] >= 80000000]['총구매액'].mean())

# df[조건] [컬럼] 평균,합,갯수
# df[ df[]>200 ] [[컬럼,컬럼]]  .평균

257547005.075846


* [QUIZ]구매주기  Min-max 스케일링 변환 후 0.5보다 큰 레코드 갯수

In [43]:
#aa = np.array([1,2,3,4])>2 

In [36]:
print(  df['구매주기'].values                     )
print(  np.array(df['구매주기'])                  )
print(  np.array(df['구매주기']).reshape(-1, 1)   )


[26  3  3 ... 18 60 31]
[26  3  3 ... 18 60 31]
[[26]
 [ 3]
 [ 3]
 ...
 [18]
 [60]
 [31]]


In [44]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['scaler_구매주기'] = scaler.fit_transform(df['구매주기'].values.reshape(-1, 1))
df['scaler_구매주기'] = scaler.fit_transform(np.array(df['구매주기']).reshape(-1, 1))
print(len(df[  df['scaler_구매주기']>0.5  ]))

65


* [QUIZ]총구매액이 평균(총구매액)보다 크면 1, 아니면 0 인 AAA컬럼 생성 후 총합 값 구하기

In [52]:
mm = df['총구매액'].mean()
idx1 = df[df['총구매액'] > mm].index
df['AAA'] = 0

df.loc[idx1, 'AAA'] = 1
print(df['AAA'].sum())

723


In [53]:
mm = df['총구매액'].mean()
df['AAA'] = df['총구매액'].apply(lambda x : 1 if x > mm else 0)
print(df['AAA'].sum())

723


In [55]:
mm = df['총구매액'].mean()
sum_v = 0
for v in df['총구매액']:
    if v > mm:
        sum_v = sum_v + 1
    else :
        0
print(sum_v)        

723


* [QUIZ]총구매액 가장큰 상위 10개 평균  - 가장적은 하위10개평균 차이

In [62]:
df = df.sort_values(by='총구매액')  #ascending=False
lw10 = df['총구매액'][:10].mean()
up10 = df['총구매액'][-10:].mean()
#print(len(up10), len(lw10))
print(up10-lw10)

1544309617.0


* [QUIZ]내점일수가 가장 많은 주구매지점과 가장 적은 주구매지점의 차이


In [64]:
print(df['내점일수'].max() - df['내점일수'].min())

221


* [QUIZ]캐주얼 상품 총구매액 - 농산물 상품 총구매액 차이

In [70]:
a = df[df['주구매상품']=='캐주얼']['총구매액'].sum()
b = df[df['주구매상품']=='농산물']['총구매액'].sum()
# print(a, b)   7835367570   30219091040
print(a-b)

-22383723470


* [QUIZ]주구매상품 중 최대 매출상품 3개의 총구매금액은 전체 총구매금액의 %인가

In [110]:
df33 = df.groupby('주구매상품')['총구매액'].sum().sort_values(ascending=False)
# print(df33.head(10))
print(df33.head(3).sum() / df['총구매액'].sum() *100)



51.35156583368913


* [QUIZ]내점당구매건수가 가장 많은 TOP 3지점 (난해한 문제...)

In [106]:
dfsort = df.sort_values(by='내점당구매건수', ascending=False)
print(dfsort['주구매지점'][:3].values)

['부평점' '분당점' '본  점']


In [112]:
df.isna().mean()

cust_id        0.000000
총구매액           0.000000
최대구매액          0.000000
환불금액           0.649073
주구매상품          0.000000
주구매지점          0.000000
내점일수           0.000000
내점당구매건수        0.000000
주말방문비율         0.000000
구매주기           0.000000
scaler_구매주기    0.000000
AAA            0.000000
dtype: float64

* [QUIZ]80% 훈련데이터 선출, 
* 총구매액 상위 25%, 하위 25% 선출, 구매주기 편차

In [131]:
int(df.shape[0] * 0.25)

620

In [133]:
df08 = df[:int(len(df) * 0.8)]
df08 = df08.sort_values('총구매액')

df25 = df08['구매주기'][:620].std()
df75 = df08['구매주기'][-620:].std()
print(df25, df75)

#df08['총구매액'].quantile(0.25)   #16034000.0
#df08['총구매액'].quantile(0.75)   #163163790.0

29.777166759482085 8.771363369680259


* df['환불금액']의 결측치를 10000000 값으로 변경 후 변경 전 과 변경 후의 전체 환불금액 차이값을 계산하시오

In [154]:
df['환불금액'].isna().sum()

1611

In [156]:
df['환불금액2'] = df['환불금액'].fillna(10000000)
print(df['환불금액'].sum() - df['환불금액2'].sum())

-16110000000.0


* [QUIZ] 환불금액 결측치를 제거한 후 내점당구매건수가 0~5:1    6~10:2  11~:3 그룹화 후 
가장 많은 집단의  내점당구매건수 총합 계산

In [184]:
idx = df[df['환불금액'].isna()].index
print(len(idx), idx[:5])
df_drop = df.drop(idx)
print(df_drop.shape)

1611 Int64Index([3, 4, 5, 7, 8], dtype='int64')
(871, 11)


In [167]:
df_drop = df.dropna(axis=0)
print(df_drop.shape)

(871, 11)


In [171]:
max(df_drop['내점당구매건수'])

14.623762376237623

In [190]:
df_drop['내점당구매건수_GRP'] = pd.cut(df_drop['내점당구매건수'], bins=[0,5,10,99999999], labels=[1,2,3])
print(df_drop['내점당구매건수_GRP'].value_counts()[0])

802


In [191]:
#df_drop[df_drop['내점당구매건수_GRP'] == 2][:30]

* [이상값] 구매주기에서 이상값 제외한 구매주기의 평균을 구하시오(이상값은 평균 에서 1.5표준편차 이상인 값）

In [192]:
Q1 = df['구매주기'].quantile(0.25)
Q3 = df['구매주기'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - (IQR*1.5)
upper = Q3 + (IQR*1.5)
df[(df['구매주기']>lower) & (df['구매주기']<upper)]['구매주기'].mean()

15.562526858616245