In [1]:
import torch
import numpy as np

# view

In [2]:
ft = torch.FloatTensor([[[0, 1, 2],
                         [3, 4, 5]],
                        [[6, 7, 8],
                         [9, 10, 11]]])

print(ft.shape)
print(ft)

torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [3]:
print(ft.view(-1, 3))
print(ft.view(-1, 3).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


# squeeze

In [4]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [5]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# unsqueeze

In [6]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [7]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [8]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# concatenate

In [9]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [10]:
torch.cat([x, y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [11]:
torch.cat([x, y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

# stacking

In [12]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(x)
print(y)
print(z)

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])


In [13]:
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [14]:
torch.stack([x, y, z], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [15]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# ones_like, zeros_like

In [16]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [17]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])