# setting

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

# linear regression

## step by step

In [3]:
x_train = torch.FloatTensor([1, 2, 3]).view(3, -1)
y_train = torch.FloatTensor([2, 4, 6]).view(3, -1)

print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [4]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [5]:
W = torch.zeros(1, requires_grad=True) # 0 초기화 및 기울기 설정
print(W)

tensor([0.], requires_grad=True)


In [6]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [7]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [8]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [10]:
optimizer.zero_grad() # gradient 0 초기화
cost.backward() # backpropagation
optimizer.step() # weight update

## whole code

In [11]:
x_train = torch.FloatTensor([1, 2, 3]).view(3, -1)
y_train = torch.FloatTensor([2, 4, 6]).view(3, -1)

# model
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

epochs = 2000
for epoch in range(epochs + 1):

    # forward
    hypothesis = x_train * W + b

    # loss
    cost = torch.mean((hypothesis - y_train) ** 2)

    # backward
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} W: {W.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

## optimizer.zero_grad()

In [12]:
import torch

w = torch.tensor(2.0, requires_grad=True)

epochs = 20
for epoch in range(epochs + 1):
    z = 2 * w
    z.backward() # optimizer.zero_grad() 안 함
    
    print(f'backward: {w.grad}') # 미분 값 누적

backward: 2.0
backward: 4.0
backward: 6.0
backward: 8.0
backward: 10.0
backward: 12.0
backward: 14.0
backward: 16.0
backward: 18.0
backward: 20.0
backward: 22.0
backward: 24.0
backward: 26.0
backward: 28.0
backward: 30.0
backward: 32.0
backward: 34.0
backward: 36.0
backward: 38.0
backward: 40.0
backward: 42.0


# autograd

# multivariable linear regression

# nn.Module

# class

# mini batch & dataloader

# customdataset