https://www.youtube.com/channel/UCK24Wy_G-6V-quKvVRjflgA/videos

# Settings

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

# Linear Regression

## step by step

In [3]:
x_train = torch.FloatTensor([1, 2, 3]).view(3, -1)
y_train = torch.FloatTensor([2, 4, 6]).view(3, -1)

print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [4]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [5]:
W = torch.zeros(1, requires_grad=True) # 0 초기화 및 기울기 설정
print(W)

tensor([0.], requires_grad=True)


In [6]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [7]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [8]:
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [9]:
optimizer = optim.SGD([W, b], lr=0.01)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [10]:
optimizer.zero_grad() # gradient 0 초기화
cost.backward() # backpropagation
optimizer.step() # weight update

## whole code

In [11]:
x_train = torch.FloatTensor([1, 2, 3]).view(3, -1)
y_train = torch.FloatTensor([2, 4, 6]).view(3, -1)

# model
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

epochs = 2000
for epoch in range(epochs + 1):

    # forward
    hypothesis = x_train * W + b

    # loss
    cost = torch.mean((hypothesis - y_train) ** 2)

    # backward
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} W: {W.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

## optimizer.zero_grad()

In [12]:
import torch

w = torch.tensor(2.0, requires_grad=True)

epochs = 20
for epoch in range(epochs + 1):
    z = 2 * w
    z.backward() # optimizer.zero_grad() 안 함
    
    print(f'backward: {w.grad}') # 미분 값 누적

backward: 2.0
backward: 4.0
backward: 6.0
backward: 8.0
backward: 10.0
backward: 12.0
backward: 14.0
backward: 16.0
backward: 18.0
backward: 20.0
backward: 22.0
backward: 24.0
backward: 26.0
backward: 28.0
backward: 30.0
backward: 32.0
backward: 34.0
backward: 36.0
backward: 38.0
backward: 40.0
backward: 42.0


# autograd

In [13]:
import torch

w = torch.tensor(2.0, requires_grad=True)

y = w ** 2
z = 2 * y + 5

z.backward()

print(w.grad)

tensor(8.)


# Multiple Linear Regression

## raw

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [15]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [16]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [17]:
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

epochs = 1000
for epoch in range(epochs):
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} w1: {w1.item():.3f} w2: {w2.item():.3f} w3: {w3.item():.3f}, b: {b.item():.3f} Cost: {cost.item():.6f}')

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297, b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676, b: 0.008 Cost: 1.563634
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677, b: 0.008 Cost: 1.497607
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677, b: 0.008 Cost: 1.435026
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678, b: 0.008 Cost: 1.375730
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678, b: 0.009 Cost: 1.319511
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679, b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679, b: 0.009 Cost: 1.215696
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679, b: 0.009 Cost: 1.167818
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680, b: 0.009 Cost: 1.122429


## vector & matrix

In [18]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

x_train.shape, y_train.shape

(torch.Size([5, 3]), torch.Size([5, 1]))

In [19]:
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

hypothesis = x_train.matmul(W) + b
hypothesis

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [20]:
optimizer = optim.SGD([W, b], lr=1e-5)
epochs = 1000
for epoch in range(epochs):
    hypothesis = x_train.matmul(W) + b
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} H: {hypothesis.squeeze().detach()} Cost: {cost.item():.6f}')

Epoch    0/1000 H: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/1000 H: tensor([154.0433, 185.0925, 175.8312, 198.5701, 141.2221]) Cost: 5.754573
Epoch  200/1000 H: tensor([154.0278, 185.0649, 175.9335, 198.5128, 141.2284]) Cost: 5.512386
Epoch  300/1000 H: tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) Cost: 5.281667
Epoch  400/1000 H: tensor([153.9960, 185.0133, 176.1295, 198.4022, 141.2426]) Cost: 5.061907
Epoch  500/1000 H: tensor([153.9797, 184.9892, 176.2233, 198.3488, 141.2504]) Cost: 4.852424
Epoch  600/1000 H: tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) Cost: 4.652731
Epoch  700/1000 H: tensor([153.9465, 184.9442, 176.4029, 198.2456, 141.2672]) Cost: 4.462265
Epoch  800/1000 H: tensor([153.9296, 184.9232, 176.4888, 198.1958, 141.2762]) Cost: 4.280604
Epoch  900/1000 H: tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]) Cost: 4.107261


# nn.Module

## Linear

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [22]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [23]:
model = nn.Linear(in_features=1, out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [24]:
optimizer = optim.SGD(model.parameters(), lr=0.01)
epochs = 2000

for epoch in range(epochs):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} Cost: {cost.item():.6f}')

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000


In [25]:
new_var = torch.FloatTensor([[4.0]])

y_pred = model(new_var) # forward
print(y_pred)

tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [26]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## Multiple

In [27]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [28]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [29]:
model = nn.Linear(in_features=3, out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [30]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)
epochs = 2000

for epoch in range(epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} Cost: {cost.item():.6f}')

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770


In [31]:
new_var = torch.FloatTensor([[73, 80, 75]])

y_pred = model(new_var)
print(y_pred)

tensor([[151.2306]], grad_fn=<AddmmBackward0>)


In [32]:
list(model.parameters())

[Parameter containing:
 tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True),
 Parameter containing:
 tensor([0.2802], requires_grad=True)]

# Class Implementation

## Linear

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [34]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [35]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(in_features=1, out_features=1)
    
    def forward(self, x):
        return self.linear(x)

In [36]:
model = LinearRegressionModel()
list(model.parameters())

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

In [37]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [38]:
epochs = 2000
for epoch in range(epochs + 1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} Cost: {cost.item():.6f}')

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


## Multiple

In [39]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [40]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [41]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(in_features=3, out_features=1)
    
    def forward(self, x):
        return self.linear(x)

In [42]:
model = MultivariateLinearRegressionModel()
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True),
 Parameter containing:
 tensor([0.2710], requires_grad=True)]

In [43]:
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [44]:
epochs = 2000
for epoch in range(epochs + 1):
    
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d}/{epochs} Cost: {cost.item():.6f}')

Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210559
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206762
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204529
Epoch 1600/2000 Cost: 0.203481
Epoch 1700/2000 Cost: 0.202486
Epoch 1800/2000 Cost: 0.201539
Epoch 1900/2000 Cost: 0.200634
Epoch 2000/2000 Cost: 0.199770


# Mini batch & DataLoader

## mini batch & batch size & iteration

In [45]:
# epoch = batch_size * iteration

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

x_train.shape, y_train.shape

(torch.Size([5, 3]), torch.Size([5, 1]))

## DataLoader

In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset, DataLoader

In [47]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

x_train.shape, y_train.shape

(torch.Size([5, 3]), torch.Size([5, 1]))

In [48]:
dataset = TensorDataset(x_train, y_train)

In [49]:
for d in dataset:
    print(d)

(tensor([73., 80., 75.]), tensor([152.]))
(tensor([93., 88., 93.]), tensor([185.]))
(tensor([89., 91., 90.]), tensor([180.]))
(tensor([ 96.,  98., 100.]), tensor([196.]))
(tensor([73., 66., 70.]), tensor([142.]))


In [50]:
dataloader = DataLoader(dataset=dataset, batch_size=2, shuffle=True)
len(dataloader)

3

In [51]:
for batch in dataloader:
    x_batch = batch[0]
    y_batch = batch[1]
    print(x_batch, y_batch)

tensor([[73., 66., 70.],
        [73., 80., 75.]]) tensor([[142.],
        [152.]])
tensor([[ 89.,  91.,  90.],
        [ 96.,  98., 100.]]) tensor([[180.],
        [196.]])
tensor([[93., 88., 93.]]) tensor([[185.]])


In [52]:
train_features, train_labels = next(iter(dataloader))
print(train_features, train_labels)

tensor([[ 73.,  80.,  75.],
        [ 96.,  98., 100.]]) tensor([[152.],
        [196.]])


In [53]:
model = nn.Linear(in_features=3, out_features=1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [54]:
epochs = 20
for epoch in range(epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print(f'Epoch {epoch:4d}/{epochs} Batch {batch_idx+1}/{len(dataloader)} Cost: {cost.item():.6f}')

Epoch    0/20 Batch 1/3 Cost: 32868.546875
Epoch    0/20 Batch 2/3 Cost: 8253.976562
Epoch    0/20 Batch 3/3 Cost: 3580.594238
Epoch    1/20 Batch 1/3 Cost: 670.870789
Epoch    1/20 Batch 2/3 Cost: 462.119263
Epoch    1/20 Batch 3/3 Cost: 113.443825
Epoch    2/20 Batch 1/3 Cost: 18.598494
Epoch    2/20 Batch 2/3 Cost: 9.061541
Epoch    2/20 Batch 3/3 Cost: 4.041673
Epoch    3/20 Batch 1/3 Cost: 0.020788
Epoch    3/20 Batch 2/3 Cost: 0.833903
Epoch    3/20 Batch 3/3 Cost: 0.693444
Epoch    4/20 Batch 1/3 Cost: 0.163755
Epoch    4/20 Batch 2/3 Cost: 0.754121
Epoch    4/20 Batch 3/3 Cost: 0.297472
Epoch    5/20 Batch 1/3 Cost: 0.393005
Epoch    5/20 Batch 2/3 Cost: 0.134999
Epoch    5/20 Batch 3/3 Cost: 0.505432
Epoch    6/20 Batch 1/3 Cost: 0.402871
Epoch    6/20 Batch 2/3 Cost: 0.228513
Epoch    6/20 Batch 3/3 Cost: 0.402366
Epoch    7/20 Batch 1/3 Cost: 0.409400
Epoch    7/20 Batch 2/3 Cost: 0.237290
Epoch    7/20 Batch 3/3 Cost: 0.213745
Epoch    8/20 Batch 1/3 Cost: 0.264171
Epoch   

In [55]:
new_var = torch.FloatTensor([[73, 80, 75]])

y_pred = model(new_var)
y_pred

tensor([[151.5295]], grad_fn=<AddmmBackward0>)

# CustomDataset

In [56]:
import torch
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader

In [57]:
class CustomDataset(Dataset):
    def __init__(self): # 데이터 전처리
        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]
        self.y_data = [[151], [185], [180], [196], [142]]
    
    def __len__(self): # 데이터셋 길이(총 샘플 수)
        return len(self.x_data)
    
    def __getitem__(self, idx): # 샘플 추출
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y

In [58]:
dataset = CustomDataset()
dataloader = DataLoader(dataset=dataset, batch_size=2, shuffle=True)

In [59]:
model = nn.Linear(in_features=3, out_features=1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [60]:
epochs = 20
for epoch in range(epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        prediction = model(x_train)
        cost = F.mse_loss(prediction, y_train)
        
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print(f'{epoch:4d}/{epochs} Batch {batch_idx+1}/{len(dataloader)} Cost: {cost.item():.6f}')

   0/20 Batch 1/3 Cost: 10398.765625
   0/20 Batch 2/3 Cost: 5092.103516
   0/20 Batch 3/3 Cost: 780.086609
   1/20 Batch 1/3 Cost: 372.490051
   1/20 Batch 2/3 Cost: 127.567596
   1/20 Batch 3/3 Cost: 45.124790
   2/20 Batch 1/3 Cost: 8.685165
   2/20 Batch 2/3 Cost: 5.587552
   2/20 Batch 3/3 Cost: 0.812518
   3/20 Batch 1/3 Cost: 0.254724
   3/20 Batch 2/3 Cost: 0.616510
   3/20 Batch 3/3 Cost: 0.013093
   4/20 Batch 1/3 Cost: 0.014322
   4/20 Batch 2/3 Cost: 0.016139
   4/20 Batch 3/3 Cost: 0.774516
   5/20 Batch 1/3 Cost: 0.312432
   5/20 Batch 2/3 Cost: 0.081949
   5/20 Batch 3/3 Cost: 0.054982
   6/20 Batch 1/3 Cost: 0.345532
   6/20 Batch 2/3 Cost: 0.024005
   6/20 Batch 3/3 Cost: 0.032789
   7/20 Batch 1/3 Cost: 0.024864
   7/20 Batch 2/3 Cost: 0.378133
   7/20 Batch 3/3 Cost: 0.031693
   8/20 Batch 1/3 Cost: 0.353172
   8/20 Batch 2/3 Cost: 0.043609
   8/20 Batch 3/3 Cost: 0.000235
   9/20 Batch 1/3 Cost: 0.005713
   9/20 Batch 2/3 Cost: 0.355695
   9/20 Batch 3/3 Cost: 0.049

In [61]:
new_var = torch.FloatTensor([[73, 80, 75]])

y_pred = model(new_var)
y_pred

tensor([[150.4308]], grad_fn=<AddmmBackward0>)