In [3]:
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
print("pandas ver = ", pd.__version__)
print("numpy ver = ", np.__version__)

pandas ver =  1.2.4
numpy ver =  1.20.1


In [8]:
# ndarray 생성
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [9]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.27946415e-307],
       [1.42418987e-306, 1.37961641e-306, 1.60220528e-306,
        1.24611266e-306],
       [9.34598925e-307, 1.24612081e-306, 1.11260755e-306,
        1.60220393e-306],
       [1.51320640e-306, 9.34609790e-307, 1.86921279e-306,
        1.24610723e-306]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
arr.shape

(2, 3)

In [23]:
arr.ndim

2

In [24]:
arr.dtype

dtype('int32')

In [25]:
arr_int = np.arange(4)
arr_int

array([0, 1, 2, 3])

In [26]:
arr_int.dtype

dtype('int32')

In [27]:
arr_float = arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

In [28]:
arr_float

array([0., 1., 2., 3.])

In [29]:
print(arr_float)

[0. 1. 2. 3.]


In [31]:
np.array(["a","b","c"])

array(['a', 'b', 'c'], dtype='<U1')

In [32]:
arr_str = np.array(["1","2","3"])

In [33]:
arr_str.dtype

dtype('<U1')

In [34]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [35]:
arr_str1 = np.array(["a","b","c"])
arr_str1.astype(np.int64)

ValueError: invalid literal for int() with base 10: 'a'

In [36]:
arr1 = np.array([[1,2],[3,4]]);arr1

array([[1, 2],
       [3, 4]])

In [46]:
arr2 =np.arange(5,9).reshape(-1,2);arr2

array([[5, 6],
       [7, 8]])

In [47]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [48]:
arr1 + 3

array([[4, 5],
       [6, 7]])

In [49]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [50]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [51]:
np.subtract(arr1, arr2)

array([[-4, -4],
       [-4, -4]])

In [52]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [53]:
arr1

array([[1, 2],
       [3, 4]])

In [54]:
arr2

array([[5, 6],
       [7, 8]])

In [56]:
(1*5 + 2*7) 

19

In [57]:
(1*6 + 2*8)

22

In [61]:
arr = np.arange(1,10).reshape(-1,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [67]:
np.arange(1,25).reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
np.arange(1,25).reshape(2,-1,4)

In [69]:
np.arange(1,25).reshape(2,3,-1)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [72]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [75]:
arr1 = arr[:2,1:3]
arr1

array([[2, 3],
       [5, 6]])

In [78]:
arr1[1,1] = 99 
arr1

array([[ 2,  3],
       [ 5, 99]])

In [79]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 99],
       [ 7,  8,  9]])

In [80]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr2 = arr[:2,1:3].copy()
arr2

array([[2, 3],
       [5, 6]])

In [82]:
arr2[1,1] = 88; arr2

array([[ 2,  3],
       [ 5, 88]])

In [83]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mutable vs immutable 

In [86]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
arr[0,2]

3

In [87]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [91]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr[arr > 3]

array([4, 5, 6])

In [94]:
idx = arr > 3 ; idx

array([[False, False, False],
       [ True,  True,  True]])

In [95]:
arr[idx]

array([4, 5, 6])