In [1]:
import torch

In [2]:
a = torch.empty(1)
b = torch.empty(2)
c = torch.empty(3)

a, b, c

(tensor([8.9082e-39]), tensor([0., 0.]), tensor([0., 0., 0.]))

In [3]:
a = torch.empty(2, 2, 3)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)

a, b, c

(tensor([[[0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.]]]),
 tensor([[0.8985, 0.1657],
         [0.8843, 0.0935]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [4]:
a = torch.ones(2, 2, dtype=torch.int)
a

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [5]:
a.size()

torch.Size([2, 2])

In [6]:
a = torch.tensor([2.5, 0.1])
a

tensor([2.5000, 0.1000])

In [7]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

x, y

(tensor([[0.9255, 0.0723],
         [0.8525, 0.0558]]),
 tensor([[0.3992, 0.9158],
         [0.1233, 0.9356]]))

In [8]:
z = x + y
z

tensor([[1.3247, 0.9880],
        [0.9758, 0.9914]])

In [9]:
z = torch.add(x, y)
z

tensor([[1.3247, 0.9880],
        [0.9758, 0.9914]])

In [10]:
y.add_(x)
y

tensor([[1.3247, 0.9880],
        [0.9758, 0.9914]])

In [11]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

x * y, torch.mul(x, y)

(tensor([[0.0340, 0.3707],
         [0.3019, 0.1790]]),
 tensor([[0.0340, 0.3707],
         [0.3019, 0.1790]]))

In [12]:
x = torch.rand(5, 3)
x

tensor([[0.1474, 0.5295, 0.5273],
        [0.3617, 0.5638, 0.4369],
        [0.8566, 0.9396, 0.9313],
        [0.0466, 0.1816, 0.8895],
        [0.0243, 0.9698, 0.3102]])

In [13]:
x[:, 0], x[1, :], x[1, 1]

(tensor([0.1474, 0.3617, 0.8566, 0.0466, 0.0243]),
 tensor([0.3617, 0.5638, 0.4369]),
 tensor(0.5638))

In [14]:
x[1, 1].item()

0.5638089776039124

In [15]:
x = torch.rand(4, 4)
x

tensor([[0.1867, 0.0460, 0.7097, 0.0589],
        [0.5569, 0.0966, 0.5882, 0.7434],
        [0.7814, 0.9444, 0.0689, 0.3456],
        [0.5973, 0.6121, 0.3007, 0.3941]])

In [16]:
x.view(16)

tensor([0.1867, 0.0460, 0.7097, 0.0589, 0.5569, 0.0966, 0.5882, 0.7434, 0.7814,
        0.9444, 0.0689, 0.3456, 0.5973, 0.6121, 0.3007, 0.3941])

In [17]:
x.view(-1)

tensor([0.1867, 0.0460, 0.7097, 0.0589, 0.5569, 0.0966, 0.5882, 0.7434, 0.7814,
        0.9444, 0.0689, 0.3456, 0.5973, 0.6121, 0.3007, 0.3941])

In [18]:
import numpy as np

In [19]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [20]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [21]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [22]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [23]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [24]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [25]:
a += 1
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))