In [1]:
import torch

In [2]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.3057, -0.3417, -0.2506], requires_grad=True)

In [3]:
y = x + 2
y

tensor([2.3057, 1.6583, 1.7494], grad_fn=<AddBackward0>)

In [4]:
z = y * y * 2
z

tensor([10.6326,  5.5001,  6.1205], grad_fn=<MulBackward0>)

In [5]:
z = z.mean()
z

tensor(7.4177, grad_fn=<MeanBackward0>)

In [6]:
z.backward() # dz/dx(only scalar)
x.grad

tensor([3.0743, 2.2111, 2.3325])

In [7]:
y = x.detach()
y

tensor([ 0.3057, -0.3417, -0.2506])

In [8]:
with torch.no_grad():
    y = x + 1
    print(y)

tensor([1.3057, 0.6583, 0.7494])


In [9]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [10]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
