# NumpPy

과학적 계산을 위한 라이브러리

데이터 분석보다, 빠른 수치 연산에 특화

ndarrya라는 다차원 배열 데이터 구조

## np 기본

In [6]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 버전 확인
print('pandas ver =', pd.__version__)
print('numpy ver =', np.__version__)

pandas ver = 1.2.4
numpy ver = 1.20.1


### arr 생성, 확인

In [19]:
# ndarrary 생성; 여러 축이기 때문에 [ ] 주의
arr = np.array([[1, 2, 3, 4], [3, 9, 2, 3]])
arr

array([[1, 2, 3, 4],
       [3, 9, 2, 3]])

In [15]:
# 초기값 n차원 arr 생성
# np.nums((a, b, c)); 초기값 nums, 각 축의 갯수 a/b/c개
print(np.zeros((2, 3)))
print(np.ones((3, 4)))
print(np.empty((3, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [38]:
# np.arange(n)으로  arr 생성
# np.arange(a, b).reshape(x, y, z, ...)
# 차원을 나누어 줌, xyz는 축, 남은 한 자리 -1 가능
arr = np.arange(1, 10)
print(arr)
arr = np.arange(1, 25).reshape(2, 3, 4)
print(arr)

[1 2 3 4 5 6 7 8 9]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [23]:
# arr 확인
arr = np.array([[1, 2, 3, 9], [7, 6, 5, 3]])
print(arr.shape) # 각 축의 개수 확인, 0, 1번 축
print(arr.ndim) # 차원 수
print(arr.dtype) # 데이터 타입

(2, 4)
2
int32


In [31]:
# 데이터 타입 변환; arr.astype(np.datatype)
arr_i = np.arange(6)
arr_f = arr_i.astype(np.float64)
print(arr_f.dtype)

arr_s = np.array(['1', '2', '3'])
print(arr_s.dtype) # 문자열
arr_i = arr_s.astype(np.int64)
print(arr_i) # 문자열에 있던 숫자는 숫자 변환 가능

float64
<U1
[1 2 3]


### arr 연산, 슬라이싱, 인덱싱

In [51]:
# arr 연산
arr1 = np.array([[1, 2, 5], [2, 6, 7]])
arr2 = np.arange(3, 9).reshape(2, 3)
arr3 = np.arange(3, 15).reshape(3, 4)
print(arr1); print(arr2); print(arr3)

# +, np.add(arr1, arr2); 각 요소 단위 더함
print(arr1 + arr2)
print(np.add(arr1, arr2))

# -, np.subtract(arr1, arr2)
print(np.add(arr1, arr2))

# * ; 각 요소 단위 곱셈
print(arr1 * arr2)

# arr1.dot(arr2); 행렬 연산
# (a, b)와 (c, d) 행렬 연산하려면 b = c일 때 연산 가능
print(arr1.dot(arr3))

[[1 2 5]
 [2 6 7]]
[[3 4 5]
 [6 7 8]]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 4  6 10]
 [ 8 13 15]]
[[ 4  6 10]
 [ 8 13 15]]
[[ 4  6 10]
 [ 8 13 15]]
[[ 3  8 25]
 [12 42 56]]
[[ 72  80  88  96]
 [125 140 155 170]]


In [77]:
# arr 슬라이싱; 매우 중요
# arr[..., c:d, a:b]; 뒤부터 0번 축
# a:b ; 0번축의 a부터 b-1까지
# c:d ; 1번축의 c부터 d-1까지
# 각 축의 범위의 교집합 조회

arr = np.arange(1, 25).reshape(-1, 3, 4)
print(arr)
# reshape(c, b, a); 0번축 a, 1번축 b, 2번축 c
# c개를 한 줄로 만들고, 그 줄을 b개 묶음으로, 다시 a개 묶음으로

print(arr[:, :2, 1:4])
# 0번축(열); 1부터 2번 인덱스
# 1번축(행); 0부터 1번 인덱스
# 2번축; 전체

print(arr[0, 2, 3])
# 0번축(열) 3번째, 1번축(행) 2번째, 2번축 0번째 인덱스

print(arr[[1, 0], [2, 1], [2, 0]])
# 0번축 2, 1번축 2, 2번 축 1 ; 23
# 0번축 0, 1번축 1, 2번축 0 ; 5

# https://acdongpgm.tistory.com/140
# https://ichi.pro/ko/numpy-indegsing-seolmyeong-214914454144013
# http://taewan.kim/post/numpy_cheat_sheet/
# https://velog.io/@kkiyou/ds1020
# https://laboputer.github.io/machine-learning/2020/04/25/numpy-quickstart/

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[[ 2  3  4]
  [ 6  7  8]]

 [[14 15 16]
  [18 19 20]]]
12
[23  5]


In [83]:
# arr 뷰 수정; 슬라이싱한 arr 수정하면 원본도 바뀜
# arr[index] = val
arr_c = arr.copy()
arr_c[0, 2, 3] = 99
print(arr_c) # 수정된 원본 확인(mutable)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 99]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [86]:
# arr 인덱싱
arr = np.arange(1, 7).reshape(2, 3)
print(arr)
print(arr> 3) # 조건에 따른 bool 출력

print(arr[arr >3]) # 조건 만족하는 데이터 추출, 배열 확인 불가

[[1 2 3]
 [4 5 6]]
[[False False False]
 [ True  True  True]]
[4 5 6]


# wine_quality example

In [88]:
import numpy as np
import pandas as pd

url_red = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
url_white = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv'

# np.loadtxt(fname=file_name, delimiter='', skiprows=n)
redwine = np.loadtxt(fname=url_red, delimiter=';', skiprows=1)
whitewine = np.loadtxt(fname=url_white, delimiter=';', skiprows=1)
# skiprows 줄 건너뛰기, delimiter 구분자 설정(기본값 \)
print(redwine); print(whitewine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]


In [94]:
# 통계값

print(redwine.sum())
print(redwine.sum(axis=0))
print(redwine.sum(axis=1))

print(redwine.mean())
print(redwine.mean(axis=0))
print(redwine.mean(axis=1))

print(redwine[:, 0].mean()) # 슬라이싱하여 통계처리

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 74.5438  123.0548   99.699   ... 100.48174 105.21547  92.49249]
7.926036165311652
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]
[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]
8.31963727329581
