## ( 실습.. sort 알고리즘 작성  ) 
1. input -> [ 2, 4, 5, 1, 3]
2. output -> [1, 2, 3, 4, 5 ]
3. sort algorithm 
4. for, if 문으로 해결 (sort관련 함수 사용 자제 ) 

In [ ]:
 a = [2,4,5,1,3]

In [ ]:
for i in range(0, len(a)-1):
    print("i = ", i) 
    for j in range(i+1, len(a)):
        print("i = {}, j = {}".format(i,j))
    print("-"*20)

i =  0
i = 0, j = 1
i = 0, j = 2
i = 0, j = 3
i = 0, j = 4
--------------------
i =  1
i = 1, j = 2
i = 1, j = 3
i = 1, j = 4
--------------------
i =  2
i = 2, j = 3
i = 2, j = 4
--------------------
i =  3
i = 3, j = 4
--------------------


In [ ]:
for i in range(0, len(a)-1):
    print("i = ", a[i]) 
    for j in range(i+1, len(a)):
        print("i = {}, j = {}".format(a[i],a[j]))
    print("-"*20)

i =  2
i = 2, j = 4
i = 2, j = 5
i = 2, j = 1
i = 2, j = 3
--------------------
i =  4
i = 4, j = 5
i = 4, j = 1
i = 4, j = 3
--------------------
i =  5
i = 5, j = 1
i = 5, j = 3
--------------------
i =  1
i = 1, j = 3
--------------------


In [ ]:
a = [2,4,5,1,3]
    
for i in range(0, len(a)-1):
    print("i = ", a[i]) 
    min_idx = i
    for j in range(i+1, len(a)):
        if a[j] < a[min_idx]:
            min_idx = j        
        print("i = {}, j = {}, min_idx = {}".format(a[i],a[j], a[min_idx]))
    a[i], a[min_idx] = a[min_idx], a[i]
    print("a = ", a)
    print("-"*20)

i =  2
i = 2, j = 4, min_idx = 2
i = 2, j = 5, min_idx = 2
i = 2, j = 1, min_idx = 1
i = 2, j = 3, min_idx = 1
a =  [1, 4, 5, 2, 3]
--------------------
i =  4
i = 4, j = 5, min_idx = 4
i = 4, j = 2, min_idx = 2
i = 4, j = 3, min_idx = 2
a =  [1, 2, 5, 4, 3]
--------------------
i =  5
i = 5, j = 4, min_idx = 4
i = 5, j = 3, min_idx = 3
a =  [1, 2, 3, 4, 5]
--------------------
i =  4
i = 4, j = 5, min_idx = 4
a =  [1, 2, 3, 4, 5]
--------------------


In [ ]:
a1 = 1
a2 = 2

In [ ]:
print(a1, a2)
tmp = a1
a1 = a2
a2 = tmp
print(a1, a2)

1 2
2 1


In [ ]:
print(a1, a2)
a1, a2 = a2, a1
print(a1, a2)

2 1
1 2


In [ ]:
a = [2,4,5,1,3]
    
for i in range(0, len(a)-1):
    min_idx = i
    for j in range(i+1, len(a)):
        if a[j] < a[min_idx]:
            min_idx = j 
    a[i], a[min_idx] = a[min_idx], a[i]

### ( 실습. sel_sort() 함수를 만들어서 실행)

In [ ]:
def sel_sort(a):
    for i in range(0, len(a)-1):
        min_idx = i
        for j in range(i+1, len(a)):
            if a[j] < a[min_idx]:
                min_idx = j 
        a[i], a[min_idx] = a[min_idx], a[i]
    print("sort result = ", a)
    return a

In [ ]:
a = [2,4,5,1,3]
sel_sort(a)

sort result =  [1, 2, 3, 4, 5]


[1, 2, 3, 4, 5]

In [ ]:
b = sel_sort(a)
print("sort 후 = ", b)

sort result =  [1, 2, 3, 4, 5]
sort 후 =  [1, 2, 3, 4, 5]


## (실습. 입력값을 임의의 숫자로 구성 ) 
1. np.random.choice

In [ ]:
import numpy as np 

np.random.choice(10,4)

array([8, 8, 0, 6])

In [ ]:
np.random.choice(10,5, replace=False) # 비복원추출 

array([8, 9, 2, 5, 3])

In [ ]:
x = np.random.choice(10,5, replace=False) # 비복원추출 
sel_sort(x)

sort result =  [2 6 7 8 9]


array([2, 6, 7, 8, 9])

In [ ]:
np.random.choice(4,3, replace=False, p=[0.2, 0.2, 0.3, 0.3]) # 비복원추출 

array([0, 3, 2])

In [ ]:
y = np.arange(10);y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(y);y

array([6, 7, 3, 5, 1, 8, 4, 0, 9, 2])

In [ ]:
np.random.seed(10)
np.random.randint(10, size=5)

array([9, 4, 0, 1, 9])

In [ ]:
def bubble_sort(a):
    n = len(a)
    while True:
        changed = False
        
        for i in range(0, n-1):
            if a[i] > a[i + 1]:
                print(a)
                a[i], a[i+1] = a[i+1], a[i]
                changed = True
                
        if changed == False:
            return

In [ ]:
x = np.random.choice(10,5, replace=False) # 비복원추출 
bubble_sort(x)

[2 0 9 5 4]
[0 2 9 5 4]
[0 2 5 9 4]
[0 2 5 4 9]
