## lec: 형변화(casting)

In [1]:
import numpy as np
import pandas as pd

# list

In [2]:
list = [1,2,3,3,4,4]
print(type(list))
print(list)

<class 'list'>
[1, 2, 3, 3, 4, 4]


#### list --> array

In [3]:
arr = np.array(list)
print(type(arr))
print(arr)
arr  # array([1, 2, 3, 3, 4, 4])

<class 'numpy.ndarray'>
[1 2 3 3 4 4]


array([1, 2, 3, 3, 4, 4])

#### list --> Series
* array-like, Iterable, dict, or scalar 

In [4]:
s = pd.Series(list)
print(s)

0    1
1    2
2    3
3    3
4    4
5    4
dtype: int64


In [5]:
pd.Series(list).value_counts()

3    2
4    2
1    1
2    1
dtype: int64

# Array

In [6]:
# arr2 = [1 2 3]  error 

#### array --> Series


In [7]:
s = pd.Series(arr)
print(s)

0    1
1    2
2    3
3    3
4    4
5    4
dtype: int32


# Dict

In [8]:
dict = {"val":[1, 2, 3, 3, 4, 4], "val2":[10, 20, 30, 30, 40, 40]}
print(type(dict))
print(dict)

<class 'dict'>
{'val': [1, 2, 3, 3, 4, 4], 'val2': [10, 20, 30, 30, 40, 40]}


In [9]:
dict.items()

dict_items([('val', [1, 2, 3, 3, 4, 4]), ('val2', [10, 20, 30, 30, 40, 40])])

In [10]:
dict.values()

dict_values([[1, 2, 3, 3, 4, 4], [10, 20, 30, 30, 40, 40]])

In [11]:
dict.keys()

dict_keys(['val', 'val2'])

In [12]:
dict["val"]

[1, 2, 3, 3, 4, 4]

In [13]:
print(np.array(dict["val"]))
np.array(dict["val"])

[1 2 3 3 4 4]


array([1, 2, 3, 3, 4, 4])

#### dict --> DataFrame

In [14]:
df = pd.DataFrame(dict)
df.head()

val  val2
0    1    10
1    2    20
2    3    30
3    3    30
4    4    40

# DataFrame
* [   [1 2 3], [1 2 3]  ]
* [   [1,2,3], [1,2,3]  ]
*     내부[] 는 행이다

In [15]:
dict = {"val":[1, 2, 3, 3, 4, 4], "val2":[10, 20, 30, 30, 40, 40]}
list = [1,2,3,3,4,4] 
arr = np.array(list)

#### list --> DataFrame

In [16]:
list = [1,2,3]
df = pd.DataFrame(list, columns = ['col'])
# df.columns = ['col']
df.head()

col
0    1
1    2
2    3

In [17]:
list = [ [1,2,3], [10,20,30]]
# df = pd.DataFrame(list, index=['col1', 'col2'])
df = pd.DataFrame(list, index = ['col1', 'col2']).T
df.head()

col1  col2
0     1    10
1     2    20
2     3    30

In [18]:
list1 = [1,2,3]
list2 = [10,20,30]
df = pd.DataFrame([list1, list2], index = ['col1', 'col2']).T
df.head()

col1  col2
0     1    10
1     2    20
2     3    30

In [19]:
list = [ [1,10], [2,20], [3,30]]
df = pd.DataFrame(list,  columns = ['col1', 'col2'])
df.head()

col1  col2
0     1    10
1     2    20
2     3    30

#### array --> DataFrame

In [20]:
list1 = [1,2,3]
list2 = [10,20,30]

In [21]:
print(np.array(list1).reshape(-1,1))
arr_reshape1 = np.array(list1).reshape(-1,1)
arr_reshape2 = np.array(list2).reshape(-1,1)

[[1]
 [2]
 [3]]


In [22]:
df = pd.DataFrame(arr_reshape1, columns=['col1'])
df['col2'] = arr_reshape2
df.head()

col1  col2
0     1    10
1     2    20
2     3    30

In [23]:
# df = pd.DataFrame()   # errpr===========Cannot set a frame with no defined index and a value
# df['col1'] = arr_reshape1
# df.head()

In [24]:
s1 = pd.Series(list1)
s2 = pd.Series(list2)
df = pd.DataFrame([ s1 ,s2 ], index = ['col1', 'col2']).T
df.head()

col1  col2
0     1    10
1     2    20
2     3    30

In [25]:
arr1 = np.array(list1)
arr2 = np.array(list2)
print(arr1)
df = pd.DataFrame([ arr1 ,arr2 ], index = ['col1', 'col2']).T
df.head()

[1 2 3]


col1  col2
0     1    10
1     2    20
2     3    30

In [26]:
s = pd.Series([1,2,3])
arr = np.array(s)
print(arr)

[1 2 3]


#### Frame화 시키기 위해선 행렬 ( [[ ]] )  꺽꺽 모양이어야된다
#### 가로(행) : [1,2,3] [1 2 3]
#### 세로(열) : [1,2,3].reshape() XXXX  [1 2 3].reshape(-1,1), pd.Series( arr, list )

#### list 꺽 --> 꺽꺽

In [27]:
list = [[1,'kim',26]]
df = pd.DataFrame( list  , columns=['seq','name','age'])
df.head()

seq name  age
0    1  kim   26

#### array 꺽 --> 꺽꺽

In [28]:
print(   [np.array(list)]   )
type(  [np.array(list)] )

[array([['1', 'kim', '26']], dtype='<U11')]


list

In [29]:
type([3])

list

### DataFrame + Series

In [30]:
list = [[1,'kim',26],[2,'hong',20]]
df = pd.DataFrame( list  , columns=['seq','name','age'])
df.head()

seq  name  age
0    1   kim   26
1    2  hong   20

* 예1)

In [31]:
df['addr'] = np.array(['서울','인천']).reshape(-1,1)
df.head()

seq  name  age addr
0    1   kim   26   서울
1    2  hong   20   인천

* 예2) 
<pre>
*  [
      ['서울'],
      ['인천']
   ]

In [32]:
df2 = pd.DataFrame([['서울'],['인천']], columns=['addr'])
df2.head()

addr
0   서울
1   인천

In [33]:
list = [[1,'kim',26],[2,'hong',20]]
df2[['seq','name','age']] = list
df2.head()

addr seq  name age
0   서울   1   kim  26
1   인천   2  hong  20

#### DataFrame 에  레코드(행) 추가

* 정석

In [34]:
list = [[1,'kim',26],[2,'hong',20]]
df = pd.DataFrame( list  , columns=['seq','name','age'])
df.head()

seq  name  age
0    1   kim   26
1    2  hong   20

In [35]:
df.loc[1]

seq        2
name    hong
age       20
Name: 1, dtype: object

In [36]:
df2.columns

Index(['addr', 'seq', 'name', 'age'], dtype='object')

In [37]:
df2 = df2.append( pd.Series(['경기',3,'park', 25], index=df2.columns), ignore_index=True)
df2.head()

addr seq  name age
0   서울   1   kim  26
1   인천   2  hong  20
2   경기   3  park  25

* 손쉬운 방법 , iloc은 신규 인덱스 불가 

In [39]:
df2.loc[2] = ['경기',3,'park', 25]
df2.head()

addr seq  name age
1   인천   2  hong  20
2   경기   3  park  25

* 레코드 한건을 삭제할 경우

In [38]:
df2 = df2.drop(index=0, axis=0)
df2.head()

addr seq  name age
1   인천   2  hong  20
2   경기   3  park  25

### DataFrame  + DataFrame/Series
* 덩어리 + 덩어리

#### DataFrame  + Series (좌우 합치기)

<img src='https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_mixed_ndim.png' width=200 height=200>

In [40]:
# --------------------------------------------------
# 2. df + srs
# pd.concat([df, srs], axis=1)
# --------------------------------------------------
s = pd.Series([66, 77, 88], name='mat22')
df = pd.concat([df2,s], axis=1) 
# df.columns = ['addr', 'seq', 'name', 'age', 'mats']
print(df.head())

  addr  seq  name  age  mat22
0  NaN  NaN   NaN  NaN     66
1   인천    2  hong   20     77
2   경기    3  park   25     88


#### DataFrame  + Series (위와래 합치기)

<img src='https://pandas.pydata.org/pandas-docs/stable/_images/merging_append_series_as_row.png' width=200 height=200>

In [41]:
s2 = pd.Series(['강원', 8, 'kang', 32, 100], index=df.columns)  #addr seq  name age  mat22
df.append(s2, ignore_index=True)

addr  seq  name  age  mat22
0  NaN  NaN   NaN  NaN     66
1   인천    2  hong   20     77
2   경기    3  park   25     88
3   강원    8  kang   32    100

#### DataFrame + DataFrame

In [42]:
emp = {"empno":[7733,7652,7799], "ename":['SMITH','KING','ALLEN'], "deptno":[10,20,30]}
emp_new = {"empno":[8899,8890], "ename":['철수','영희'], "deptno":[10,10]}
emp_old = {"empno":[337,445], "ename":['OLD_MAN','OLD_FEM'], "deptno":[30,30]}
dept = {"deptno":[10,20,30,40], "loc":["LA","KOR","NY","CHICAGO"]}

emp_df = pd.DataFrame(emp)
emp_new_df = pd.DataFrame(emp_new)
emp_old_df = pd.DataFrame(emp_old)
dept_df = pd.DataFrame(dept)

print(emp_df.head())
print(emp_new_df.head())
print(emp_old_df.head())
print(dept_df.head())
    

   empno  ename  deptno
0   7733  SMITH      10
1   7652   KING      20
2   7799  ALLEN      30
   empno ename  deptno
0   8899    철수      10
1   8890    영희      10
   empno    ename  deptno
0    337  OLD_MAN      30
1    445  OLD_FEM      30
   deptno      loc
0      10       LA
1      20      KOR
2      30       NY
3      40  CHICAGO


#### concat, append, join, merge
* ref : https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
---
* Concat : gives the flexibility to join based on the axis( all rows or all columns)
 - Append  : is the specific case(axis=0, join='outer') of concat
* Join    : is based on the indexes (set by set_index) on how variable =['left','right','inner','couter']
* Merge  : is based on any particular column each of the two dataframes, this columns are variables on like 'left_on', 'right_on', 'on'


* 미션1) 모든 emp프레임 합치기  결과: emp_all_df로 저장<br>
<img src='https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_basic.png' width=100 height=100>

In [43]:
emp_all_df = pd.concat([emp_df, emp_new_df,emp_old_df], ignore_index=True)
emp_all_df

empno    ename  deptno
0   7733    SMITH      10
1   7652     KING      20
2   7799    ALLEN      30
3   8899       철수      10
4   8890       영희      10
5    337  OLD_MAN      30
6    445  OLD_FEM      30

In [44]:
emp_df.append([emp_new_df,emp_old_df], ignore_index=True)

empno    ename  deptno
0   7733    SMITH      10
1   7652     KING      20
2   7799    ALLEN      30
3   8899       철수      10
4   8890       영희      10
5    337  OLD_MAN      30
6    445  OLD_FEM      30

### MERGE & CONCAT
---
pd.merge(
    left,
    right,
    how="inner",
    on=None,
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None,
)
---
pd.concat(
    objs,
    axis=0,
    join="outer",
    ignore_index=False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity=False,
    copy=True,
)
---
<font color=red>
* inner : INNER JOIN<br>
* left : LEFT OUTER JOIN <br>
* right : RIGHT OUTER JOIN <br>
* outer : FULL OUTER JOIN <br>
</font>

* 미션2) emp_all_df 과 dept_df inner 조인   결과: emp_dept_inner로 저장<br>
<img src='https://pandas.pydata.org/pandas-docs/stable/_images/merging_concat_axis1_inner.png' width=200 height=200>

In [45]:
#XXXXXXXX 잘못된 합치기
pd.concat([emp_all_df, dept_df], axis=1) 

empno    ename  deptno  deptno      loc
0   7733    SMITH      10    10.0       LA
1   7652     KING      20    20.0      KOR
2   7799    ALLEN      30    30.0       NY
3   8899       철수      10    40.0  CHICAGO
4   8890       영희      10     NaN      NaN
5    337  OLD_MAN      30     NaN      NaN
6    445  OLD_FEM      30     NaN      NaN

# <font color='red'>TODO</font>

In [59]:
concat_df = pd.concat([emp_all_df, dept_df], axis=0, join="inner", ignore_index=True)
concat_df

deptno
0       10
1       20
2       30
3       10
4       10
5       30
6       30
7       10
8       20
9       30
10      40

In [53]:
emp_dept_inner = pd.merge(emp_all_df, dept_df, how="inner", on='deptno')
emp_dept_inner

empno    ename  deptno  loc
0   7733    SMITH      10   LA
1   8899       철수      10   LA
2   8890       영희      10   LA
3   7652     KING      20  KOR
4   7799    ALLEN      30   NY
5    337  OLD_MAN      30   NY
6    445  OLD_FEM      30   NY

* 미션3) emp_all_df 과 dept_df left_outer 조인    결과: emp_dept_leftouter로 저장<br>
<img src='https://pandas.pydata.org/pandas-docs/stable/_images/merging_merge_on_key.png' width=300 height=300><br>

In [48]:
emp_dept_leftouter = pd.merge(emp_all_df, dept_df,how="left", on='deptno')
emp_dept_leftouter

empno    ename  deptno  loc
0   7733    SMITH      10   LA
1   7652     KING      20  KOR
2   7799    ALLEN      30   NY
3   8899       철수      10   LA
4   8890       영희      10   LA
5    337  OLD_MAN      30   NY
6    445  OLD_FEM      30   NY

* 미션4) emp_all_df 과 dept_df right_outer 조인    결과: emp_dept_rightouter로 저장

In [49]:
emp_dept_rightouter = pd.merge(emp_all_df, dept_df,how="right", on='deptno')
emp_dept_rightouter

empno    ename  deptno      loc
0  7733.0    SMITH      10       LA
1  8899.0       철수      10       LA
2  8890.0       영희      10       LA
3  7652.0     KING      20      KOR
4  7799.0    ALLEN      30       NY
5   337.0  OLD_MAN      30       NY
6   445.0  OLD_FEM      30       NY
7     NaN      NaN      40  CHICAGO

* 미션5) emp_all_df 과 dept_df  full_outer 조인 결과 : emp_dept_fullouter로 저장

In [60]:
s2 = pd.Series([1111, 'LKH', 50], index=emp_all_df.columns)  #addr seq  name age  mat22
emp_all_df.append(s2, ignore_index=True)

empno    ename  deptno
0   7733    SMITH      10
1   7652     KING      20
2   7799    ALLEN      30
3   8899       철수      10
4   8890       영희      10
5    337  OLD_MAN      30
6    445  OLD_FEM      30
7   1111      LKH      50

In [61]:
emp_dept_fullouter = pd.merge(emp_all_df, dept_df, how="outer", on='deptno')
emp_dept_fullouter

empno    ename  deptno      loc
0  7733.0    SMITH      10       LA
1  8899.0       철수      10       LA
2  8890.0       영희      10       LA
3  7652.0     KING      20      KOR
4  7799.0    ALLEN      30       NY
5   337.0  OLD_MAN      30       NY
6   445.0  OLD_FEM      30       NY
7     NaN      NaN      40  CHICAGO

#### 분석 API 활용

In [51]:
from sklearn.preproc

SyntaxError: invalid syntax (Temp/ipykernel_19312/1978695627.py, line 1)