In [1]:
import random

a = random.random() # 0~1
b = random.uniform(1, 10) # float
c = random.randint(1, 10) # int
d = random.randrange(1, 10) # int
e = random.normalvariate(0, 1) # normal distribution
print(a)
print(b)
print(c)
print(d)
print(e)

0.8879242876488532
4.324213004560776
5
7
0.3863808746735083


In [2]:
random.seed(1)

mylist = list('ABCDEFGH')
print(mylist)

a = random.choice(mylist)
b = random.sample(mylist, 3)
c = random.choices(mylist, k=3) # multiple
random.shuffle(mylist)
print(a)
print(b)
print(c)
print(mylist)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
C
['B', 'C', 'A']
['D', 'D', 'F']
['C', 'E', 'B', 'F', 'G', 'H', 'A', 'D']


In [3]:
import secrets

mylist = list('ABCDEFGH')

a = secrets.randbelow(10)
b = secrets.randbits(4) # 4bits
c = secrets.choice(mylist)
print(a)
print(b)
print(c)

1
3
C


In [4]:
import numpy as np

np.random.seed(1)

a = np.random.rand(3) # float
b = np.random.rand(2, 3)
c = np.random.randint(low=0, high=10, size=(2, 3)) # int
print(a)
print(b)
print(c)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
np.random.shuffle(arr) # shuffle in first axis
print(arr)

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[0.30233257 0.14675589 0.09233859]
 [0.18626021 0.34556073 0.39676747]]
[[2 4 5]
 [2 4 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
